insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Автономная область','а.обл.','109');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Автономный округ','а.окр.','110');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Автономный округ','АО','101');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Автономная область','Аобл','102');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Город','г','103');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Город','г.','111');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Город федерального значения','г.ф.з.','112');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Край','край','104');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Область','обл','105');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Область','обл.','113');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Округ','округ','107');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Республика','Респ','106');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Республика','респ.','114');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(1,'Чувашия','Чувашия','108');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(2,'Автономный округ','АО','201');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Автономный округ','АО','305');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Внутригородская территория','вн.тер. г.','307');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Городской округ','г.о.','308');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Муниципальный район','м.р-н','309');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Поселение','п','306');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Поселение','пос.','310');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Район','р-н','301');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Территория','тер','303');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Улус','у','302');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(3,'Улус','у.','311');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Волость','волость','410');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Город','г','401');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Город','г.','418');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Дачный поселок','дп','405');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Курортный поселок','кп','404');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Массив','массив','416');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Поселок','п','417');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Почтовое отделение','п/о','411');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Поселок городского типа','пгт','402');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Рабочий поселок','рп','403');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Сельская администрация','с/а','407');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Сельское муницип.образование','с/мо','415');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Сельский округ','с/о','409');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Сельское поселение','с/п','414');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Сельсовет','с/с','406');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(4,'Территория','тер','412');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(5,'Район','р-н','503');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(5,'Территория','тер','502');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Аал','аал','601');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Автодорога','автодорога','645');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Арбан','арбан','640');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Аул','аул','602');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Волость','волость','603');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Выселки(ок)','высел','604');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Город','г','605');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Городок','городок','636');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'городской поселок','гп','649');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Деревня','д','606');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Дачный поселок','дп','607');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Железнодорожная будка','ж/д_будка','608');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Железнодорожная казарма','ж/д_казарм','609');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'ж/д останов. (обгонный) пункт','ж/д_оп','610');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Железнодорожная платформа','ж/д_платф','638');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Железнодорожный пост','ж/д_пост','611');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Железнодорожный разъезд','ж/д_рзд','612');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Железнодорожная станция','ж/д_ст','613');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Жилая зона','жилзона','647');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Жилой район','жилрайон','646');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Заимка','заимка','614');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Казарма','казарма','615');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Квартал','кв-л','639');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Кордон','кордон','644');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Курортный поселок','кп','616');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Леспромхоз','лпх','642');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Местечко','м','617');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Массив','массив','648');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Микрорайон','мкр','618');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Населенный пункт','нп','619');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Остров','остров','620');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Поселок','п','621');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Почтовое отделение','п/о','626');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Планировочный район','п/р','622');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Поселок и(при) станция(и)','п/ст','623');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Поселок городского типа','пгт','624');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Погост','погост','643');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Починок','починок','625');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Промышленная зона','промзона','627');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Разъезд','рзд','628');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Рабочий поселок','рп','629');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Село','с','630');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Слобода','сл','631');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Садовое неком-е товарищество','снт','641');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Станция','ст','632');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Станица','ст-ца','633');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Территория','тер','637');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Улус','у','634');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(6,'Хутор','х','635');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Абонентский ящик','а/я','772');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Аллея','ал.','765');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Аллея','аллея','701');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Балка','балка','781');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Берег','берег','773');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Бульвар','б-р','702');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Бугор','бугор','776');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Бухта','бухта','782');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Вал','вал','768');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Взвоз','взв.','791');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Въезд','въезд','703');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Городок','городок','735');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Гаражно-строит-ный кооператив','гск','763');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Деревня','д','736');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Дачное неком-е партнерство','днп','787');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Дорога','дор','704');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Железнодорожная будка','ж/д_будка','737');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Железнодорожная казарма','ж/д_казарм','738');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'ж/д останов. (обгонный) пункт','ж/д_оп','739');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Железнодорожная платформа','ж/д_платф','759');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Железнодорожный пост','ж/д_пост','740');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Железнодорожный разъезд','ж/д_рзд','741');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Железнодорожная станция','ж/д_ст','742');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Животноводческая точка','жт','705');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Заезд','заезд','706');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Заезд','ззд.','794');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Зона','зона','777');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Казарма','казарма','743');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Канал','канал','762');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Квартал','кв-л','707');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Километр','км','708');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Кольцо','кольцо','709');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Коса','коса','767');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Кольцо','к-цо','795');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Линия','линия','710');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Линия','лн.','796');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Местечко','м','744');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Маяк','маяк','785');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Магистраль','мгстр.','797');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Местность','местность','780');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Микрорайон','мкр','745');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Мост','мост','770');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Некоммерческое партнерство','н/п','788');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Набережная','наб','711');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Набережная','наб.','798');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Населенный пункт','нп','746');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Остров','остров','712');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Поселок','п','748');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Почтовое отделение','п/о','749');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Планировочный район','п/р','750');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Поселок и(при) станция(и)','п/ст','751');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Парк','парк','713');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Переулок','пер','714');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Переулок','пер.','799');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Переезд','пер-д','783');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Переезд','переезд','715');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Площадь','пл','716');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Платформа','платф','747');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Площадка','пл-ка','717');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Полустанок','полустанок','752');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проезд','пр-д','732');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Просек','пр-к','733');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Просека','пр-ка','734');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проспект','пр-кт','719');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проселок','пр-лок','753');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проезд','проезд','718');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Промзона','промзона','790');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Просек','просек','720');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Просека','просека','774');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проселок','проселок','721');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проток','проток','766');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проулок','проул.','760');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Проулок','проулок','722');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Разъезд','рзд','754');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Разъезд','рзд.','775');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Ряд(ы)','ряд','778');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Ряды','ряды','771');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Село','с','755');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Сад','сад','723');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Съезд','сзд.','784');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Спуск','с-к','786');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Сквер','сквер','724');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Слобода','сл','756');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Садовое неком-е товарищество','снт','764');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Спуск','спуск','761');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Сквер','с-р','792');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Станция','ст','757');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Строение','стр','725');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Территория','тер','726');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'тоннель','тоннель','779');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Тракт','тракт','727');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Тупик','туп','728');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Улица','ул','729');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Участок','уч-к','730');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Фермерское хозяйство','ф/х','789');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Ферма','ферма','769');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Хутор','х','758');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Шоссе','ш','731');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(7,'Шоссе','ш.','793');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Владение','влд.','802');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Дом','д.','803');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Домовладение','двлд.','804');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Дом','ДОМ','801');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Здание','зд.','805');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Корпус','к.','806');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Котельная','кот.','807');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Объект незав. строительства','ОНС','808');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Павильон','пав.','809');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Сооружение','соор.','810');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(8,'Строение','стр.','811');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Гараж','г-ж','901');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Квартира','кв.','902');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Комната','ком.','903');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Офис','офис','904');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Погреб','п-б','905');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Подвал','подв.','906');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Помещение','помещ.','907');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Рабочий участок','раб.уч.','908');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Склад','скл.','909');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Торговый зал','торг. зал','910');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(9,'Цех','цех','911');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(35,'Внутригородской район','вн.р-н','3501');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(35,'Городское поселение','г. п.','3502');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(35,'Сельское поселение','с.п.','3503');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(35,'Сельсовет','с/с','3504');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Абонентский ящик','а/я','6532');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Аал','аал','6534');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Аллея','ал.','6535');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Арбан','арбан','6536');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Аул','аул','6537');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Балка','балка','6533');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Берег','б-г','6501');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Бульвар','б-р','6538');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Вал','вал','6502');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Въезд','взд.','6539');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Городок','г-к','6540');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Гаражно-строительный кооператив','гск','6579');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Деревня','д.','6541');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Дачное неком-е партнерство','днп','6580');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Дорога','дор.','6542');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Железнодорожная будка','ж/д б-ка','6543');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Железнодорожная казарма','ж/д к-ма','6544');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Железнодорожная платформа','ж/д пл-ма','6545');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Железнодорожный разъезд','ж/д рзд.','6546');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Железнодорожная станция','ж/д ст.','6547');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Жилой район','ж/р','6503');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Заезд','ззд.','6548');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Зона (массив)','зона','6504');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Квартал','кв-л','6505');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Километр','км','6549');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Коса','коса','6550');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Кольцо','к-цо','6551');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Линия','лн.','6552');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Местность','местность','6581');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Местечко','м-ко','6553');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Микрорайон','мкр','6582');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Микрорайон','мкр.','6506');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Некоммерческое партнерство','н/п','6583');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Набережная','наб.','6554');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Остров','ост-в','6507');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Поселок','п.','6555');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Промышленный район','п/р','6508');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Парк','парк','6509');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Переулок','пер.','6556');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Переезд','пер-д','6557');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Починок','п-к','6558');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Площадь','пл.','6559');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Платформа','платф.','6510');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Площадка','пл-ка','6560');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Проезд','пр-д','6561');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Просек','пр-к','6562');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Просека','пр-ка','6563');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Проспект','пр-кт','6564');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Проселок','пр-лок','6565');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Промышленная зона','промзона','6584');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Проулок','проул.','6566');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Разъезд','рзд.','6567');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Район','р-н','6511');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Село','с.','6568');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Сад','сад','6512');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Спуск','с-к','6569');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Сквер','сквер','6513');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Слобода','сл.','6570');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Садовое товарищество','снт','6585');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Сквер','с-р','6571');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Станция','ст.','6572');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Строение','стр.','6573');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория','тер','6586');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория','тер.','6514');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория гаражно-строительного кооператива','тер. ГСК','6515');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория дачных некоммерческих объединений гражд','тер. ДНО','6516');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория дачных некоммерческих партнерств','тер. ДНП','6517');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория дачных некоммерческих товариществ','тер. ДНТ','6518');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория дачных потребительских кооперативов','тер. ДПК','6519');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория огороднических некоммерческих объединен','тер. ОНО','6520');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория огороднических некоммерческих партнерст','тер. ОНП','6521');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория огороднических некоммерческих товарищес','тер. ОНТ','6522');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория огороднических потребительских кооперат','тер. ОПК','6523');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория садоводческих некоммерческих объединени','тер. СНО','6524');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория садоводческих некоммерческих партнерств','тер. СНП','6525');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория садоводческих некоммерческих товарищест','тер. СНТ','6526');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория садоводческих потребительских кооперати','тер. СПК','6527');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория товарищества собственников недвижимости','тер. ТСН','6528');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Территория фермерского хозяйства','тер.ф.х.','6529');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Тракт','тракт','6574');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Тупик','туп.','6575');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Улица','ул.','6576');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Усадьба','ус.','6530');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Фермерское хозяйство','ф/х','6587');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Хутор','х.','6577');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Шоссе','ш.','6578');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(65,'Юрты','ю.','6531');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(75,'Земельный участок','з/у','7501');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Гаражно-строительный кооператив','гск','9004');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Дачное неком-е партнерство','днп','9010');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Местность','местность','9011');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Микрорайон','мкр','9006');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Некоммерческое партнерство','н/п','9009');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Промышленная зона','промзона','9003');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Сад','сад','9007');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Садовое товарищество','снт','9002');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Территория','тер','9005');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(90,'Фермерское хозяйство','ф/х','9008');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Абонентский ящик','а/я','9172');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Аал','аал','9132');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Аллея','аллея','9101');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Арбан','арбан','9160');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Аул','аул','9133');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Берег','берег','9173');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Бульвар','б-р','9102');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Бугор','бугор','9176');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Вал','вал','9168');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Въезд','въезд','9103');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Выселки(ок)','высел','9134');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Городок','городок','9135');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Гаражно-строит-ный кооператив','гск','9163');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Деревня','д','9136');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Дорога','дор','9104');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Железнодорожная будка','ж/д_будка','9137');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Железнодорожная казарма','ж/д_казарм','9138');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'ж/д останов. (обгонный) пункт','ж/д_оп','9139');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Железнодорожная платформа','ж/д_платф','9159');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Железнодорожный пост','ж/д_пост','9140');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Железнодорожный разъезд','ж/д_рзд','9141');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Железнодорожная станция','ж/д_ст','9142');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Животноводческая точка','жт','9105');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Заезд','заезд','9106');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Зона','зона','9177');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Казарма','казарма','9143');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Канал','канал','9162');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Квартал','кв-л','9107');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Километр','км','9108');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Кольцо','кольцо','9109');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Коса','коса','9167');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Линия','линия','9110');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Местечко','м','9144');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Микрорайон','мкр','9145');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Мост','мост','9170');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Набережная','наб','9111');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Населенный пункт','нп','9146');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Остров','остров','9112');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Поселок','п','9148');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Почтовое отделение','п/о','9149');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Планировочный район','п/р','9150');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Поселок и(при) станция(и)','п/ст','9151');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Парк','парк','9113');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Переулок','пер','9114');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Переезд','переезд','9115');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Площадь','пл','9116');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Платформа','платф','9147');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Площадка','пл-ка','9117');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Полустанок','полустанок','9152');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Починок','починок','9153');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Проспект','пр-кт','9119');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Проезд','проезд','9118');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Просек','просек','9120');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Просека','просека','9174');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Проселок','проселок','9121');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Проток','проток','9166');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Проулок','проулок','9122');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Разъезд','рзд','9154');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Ряды','ряды','9171');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Село','с','9155');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Сад','сад','9123');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Сквер','сквер','9124');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Слобода','сл','9156');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Садовое неком-е товарищество','снт','9164');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Спуск','спуск','9161');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Станция','ст','9157');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Строение','стр','9125');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Территория','тер','9126');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Тракт','тракт','9127');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Тупик','туп','9128');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Улица','ул','9129');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Участок','уч-к','9130');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Ферма','ферма','9169');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Хутор','х','9158');
insert into fias_socrbase(lev,socrname,scname,kod_t_st) values(91,'Шоссе','ш','9131');
