insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'214','По месту нахождения российской организации',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'120','По месту жительства индивидуального предпринимателя',1,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'217','По месту учета правопреемника российской организации',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'220','по месту нахождения обособленного подразделения российской организации',0,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'222','По месту учета российской организации по месту нахождения обособленного подразделения',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'320','по месту осуществления деятельности индивидуального предпринимателя',0,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'335','По месту нахождения обособленного подразделения иностранной организации в Российской Федерации',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'350','По месту учета международной организации в Российской Федерации',1,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'112','По месту жительства физического лица, не признаваемого индивидуальным предпринимателем',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'121','По месту жительства адвоката, учредившего адвокатский кабинет',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'122','По месту жительства нотариуса, занимающегося частной практикой',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'124','По месту жительства члена (главы) крестьянского (фермерского) хозяйства',1,0);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'125','по месту жительства адвоката',0,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'126','по месту жительства нотариуса',0,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'212','по месту учета российской организации',0,1);
insert into ref_book_present_place(id,record_id,version,status,code,name,for_ndfl,for_fond) values(seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2016','dd.mm.yyyy'),0,'213','по месту учета в качестве крупнейшего налогоплательщика',0,1);

update ref_book_present_place set for_fond=0;
update ref_book_present_place set for_fond=1 where code between '112' and '124' or code in ('214','217','222','335','350');

update ref_book_present_place set for_ndfl=0;
update ref_book_present_place set for_ndfl=1 where code='120' or code between '125' and '213' or code in ('220','320','350');
