
GRANT EXECUTE ON TAX.Add_Log_System_NDFL TO NDFL;
GRANT REFERENCES ON TAX.department TO NDFL;
GRANT REFERENCES ON TAX.sec_role TO NDFL;
GRANT REFERENCES ON TAX.sec_user_role TO NDFL;
GRANT REFERENCES ON TAX.sec_user TO NDFL;
GRANT SELECT ON TAX.sec_role TO NDFL;
GRANT SELECT ON TAX.sec_user TO NDFL;
GRANT SELECT ON TAX.sec_user_role TO NDFL;
GRANT SELECT ON TAX.department TO NDFL;
GRANT SELECT ON TAX.subsystem_role TO NDFL;
GRANT SELECT ON TAX.vw_log_table_change TO NDFL;
