
package com.aplana.sbrf.taxaccounting.web.module.audit.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://taxaccounting.sbrf.aplana.com/AuditManagementService/")
public class AuditManagementServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AuditManagementServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AuditManagementServiceException_Exception(String message, AuditManagementServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AuditManagementServiceException_Exception(String message, AuditManagementServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.aplana.sbrf.taxaccounting.web.module.audit.ws.AuditManagementServiceException
     */
    public AuditManagementServiceException getFaultInfo() {
        return faultInfo;
    }

}
