insert into dict_tax_period (code, name, I, T, P, V, D) values ('1', 'январь', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('2', 'февраль', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('3', 'март', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('4', 'апрель', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('5', 'май', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('6', 'июнь', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('7', 'июль', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('8', 'август', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('9', 'сентябрь', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('10', 'октябрь', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('11', 'ноябрь', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('12', 'декабрь', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('13', 'первый квартал по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('14', 'полугодие по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('15', 'девять месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('16', 'год по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('21', 'первый квартал', 1, 1, 1, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('22', 'второй квартал', 0, 0, 0, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('23', 'третий квартал', 0, 0, 0, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('24', 'четвёртый квартал', 0, 0, 0, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('25', 'первый квартал в случае представления налоговой декларации управляющим товарищем', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('26', 'второй квартал в случае представления налоговой декларации управляющим товарищем', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('27', 'третий квартал в случае представления налоговой декларации управляющим товарищем', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('28', 'четвёртый квартал в случае представления налоговой декларации управляющим товарищем', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('31', 'полугодие', 1, 1, 1, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('33', 'девять месяцев', 1, 1, 1, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('34', 'год', 1, 1, 1, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('35', 'один месяц', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('36', 'два месяца', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('37', 'три месяца', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('38', 'четыре месяца', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('39', 'пять месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('40', 'шесть месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('41', 'семь месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('42', 'восемь месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('43', 'девять месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('44', 'десять месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('45', 'одиннадцать месяцев', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('46', 'год', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('50', 'последний налоговый период при реорганизации (ликвидации) организации', 1, 1, 1, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('51', 'первый квартал при ликвидации организации', 0, 0, 1, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('52', 'полугодие при реорганизации организации', 0, 0, 1, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('53', '9 месяцев при реорганизации организации', 0, 0, 1, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('54', 'второй квартал при ликвидации организации', 0, 0, 0, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('55', 'третий квартал при ликвидации организации', 0, 0, 0, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('56', 'четвёртый квартал при ликвидации организации', 0, 0, 0, 1, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('57', 'один месяц по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('58', 'два месяца по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('59', 'три месяца по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('60', 'четыре месяца по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('61', 'пять месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('62', 'шесть месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('63', 'семь месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('64', 'восемь месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('65', 'девять месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('66', 'десять месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('67', 'одиннадцать месяцев по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('68', 'год по консолидированной группе налогоплательщиков', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('71', 'за январь при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('72', 'за февраль при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('73', 'за март при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('74', 'за апрель при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('75', 'за май при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('76', 'за июнь при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('77', 'за июль при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('78', 'за август при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('79', 'за сентябрь при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('80', 'за октябрь при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('81', 'за ноябрь при ликвидации организации', 0, 0, 0, 0, 0);
insert into dict_tax_period (code, name, I, T, P, V, D) values ('82', 'за декабрь при ликвидации организации', 0, 0, 0, 0, 0);