INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (0, 'Тест', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (2, 'Коды представления налоговой декларации по месту нахождения (учёта)', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (3, 'Коды ОКАТО', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (4, 'Коды субъектов Российской Федерации', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (5, 'Коды форм реорганизации и ликвидации организации', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (6, 'Коды налоговых льгот', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (7, 'Параметры налоговых льгот', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (8, 'Коды, определяющие налоговый (отчётный) период', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (9,'Организации-участники контролируемых сделок', 0);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (10,'ОК 025-2001 (Общероссийский классификатор стран мира)', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (11,'Услуги в части программного обеспечения', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (12,'Коды единиц измерения на основании ОКЕИ', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (13,'Виды услуг', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (14,'Режимы переговорных сделок', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (15,'Общероссийский классификатор валют', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (16,'Типы сделок', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (17,'Коды драгоценных металлов', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (18,'Признаки физической поставки', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (20,'Направленности сделок', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (22, 'Курсы Валют', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (23, 'Ставки рефинансирования ЦБ РФ', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (24, 'Коды видов платежей', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (25, 'Признак возложения обязанности по уплате налога на обособленное подразделение', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (26, 'Признак составления расчёта', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (27, 'Классификатор расходов Сбербанка России для целей налогового учёта', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (28, 'Классификатор доходов Сбербанка России для целей налогового учёта', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (29, 'Классификатор соответствия счетов бухгалтерского учёта кодам налогового учёта', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (30, 'Подразделения', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (31, 'Параметры подразделения по транспортному налогу', 0);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (33, 'Параметры подразделения по налогу на прибыль', 0);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (34, 'Общероссийский классификатор видов экономической деятельности', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (35, 'Признак лица, подписавшего документ', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (36,'Признак сделки, совершенной в РПС', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (37,'Параметры подразделения по УКС', 0);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (38,'Да/Нет', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (40, 'Экологические классы', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (41, 'Ставки транспортного налога', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (42, 'Коды видов транспортных средств', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (50, 'Оборотная ведомость (Форма 0409101-СБ)', 0);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (52, 'Отчет о прибылях и убытках (Форма 0409102-СБ)', 0);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (60, 'Части сделок', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (61, 'Коды сделок', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (62, 'Признаки ценных бумаг', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (63, 'Коды условий поставки', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (64, 'Коды типов предмета сделки', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (65, 'Коды стороны сделки', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (66, 'Коды основания признания цены рыночной', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (67, 'Коды наименования сделки', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (68, 'Коды  ОКП  на  основании  общероссийского  классификатора  продукции  (ОКП)', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (69, 'Признаки взаимозависимости', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (70, 'Сведения об организации', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (71, 'Амортизационные группы', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (72, 'Процентные ставки', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (73, 'Товарная номенклатура внешнеэкономической деятельности таможенного союза', 1);
INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (74, 'Пользователи', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (80, 'Виды изменений', 1);

INSERT INTO REF_BOOK (ID, NAME, VISIBLE) VALUES (85, 'Виды срочных сделок', 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (3,	2,	'Код',										'CODE',				1,		0,		null,	null,	1,	null,	3, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (4,	2,	'Наименование',								'NAME',				1,		1,		null,	null,	1,	null,	510, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (8,	3,	'Наименование муниципального образования',	'NAME',				1,		3,		null,	null,	1,	null,	510, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (6,	3,	'Идентификатор родительской записи',		'PARENT_ID',		4,		1,		3,		8,		1,	null,	510, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (7,	3,	'Код ОКАТО',								'OKATO',			1,		2,		null,	null,	1,	null,	11, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (9,	4,	'Код',										'CODE',				1,		0,		null,	null,	1,	null,	2 , 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (10,	4,	'Наименование',								'NAME',				1,		1,		null,	null,	1,	null,	510, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (11,	4,	'Код ОКАТО',								'OKATO',			4,		2,		3,		7,		1,	null,	11, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (12,	4,	'Определяющая часть кода ОКАТО',			'OKATO_DEFINITION',	1,		3,		null,	null,	1,	null,	11, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (13,	5,	'Код',										'CODE',				1,		0,		null,	null,	1,	null,	1, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (14,	5,	'Наименование',								'NAME',				1,		1,		null,	null,	1,	null,	510, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (15,	6,	'Код',										'CODE',				1,		0,		null,	null,	1,	null,	10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (16,	6,	'Наименование льготы',						'NAME',				1,		1,		null,	null,	1,	null,	100, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (300,6,	'Идентификатор родительской записи',		'PARENT_ID',		4,		2,		6,		16,		1,	null,	100, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (17,	7,	'Код',										'CODE',				2,		0,		null,	null,	1,	0,		9, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (18,	7,	'Код региона',								'DICT_REGION_ID',	4,		1,		4,		10,		1,	null,	510, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (19,	7,	'Код налоговой  льготы',					'TAX_BENEFIT_ID',	4,		2,		6,		16,		1,	null,	4000, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (20,	7,	'Основание - статья',						'SECTION',			1,		3,		null,	null,	1,	null,	4, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (21,	7,	'Основание - пункт',						'ITEM',				1,		4,		null,	null,	1,	null,	4, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (22,	7,	'Основание - подпункт',						'SUBITEM',			1,		5,		null,	null,	1,	null,	4, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (23,	7,	'Уменьшающий процент, %',					'PERCENT',			2,		6,		null,	null,	1,	2,		6, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (24,	7,	'Пониженная ставка',						'RATE',				2,		7,		null,	null,	1,	2,		20, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (25,	8,	'Код',										'CODE',				1,		0,		null,	null,	1,	null,	2, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (26,	8,	'Наименование',								'NAME',				1,		1,		null,	null,	1,	null,	510, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (27,	8,	'Принадлежность к налогу на прибыль',		'I',				2,		2,		null,	null,	0,	0,		10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (28,	8,	'Принадлежность к транспортному налогу',	'T',				2,		3,		null,	null,	0,	0,		10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (29,	8,	'Принадлежность к налогу на имущество',		'P',				2,		4,		null,	null,	0,	0,		10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (30,	8,	'Принадлежность к налогу НДС',				'V',				2,		5,		null,	null,	0,	0,		10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (31,	8,	'Принадлежность к ТЦО',						'D',				2,		6,		null,	null,	0,	0,		10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (623,8,  'Порядок следования',						'ORD',    		    2,      7,      null,   null,   0,  0,      10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (624,8,  'Количество месяцев',						'MONTHS',       	2,      8,      null,   null,   1,  0,      10, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (50,10,'Код','CODE',1,0,null,null,1,null,3,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (51,10,'Код (2-х букв.)','CODE_2',1,1,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (52,10,'Код (3-х букв.)','CODE_3',1,2,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (53,10,'Краткое наименование','NAME',1,3,null,null,1,null,100,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (54,10,'Полное наименование','FULLNAME',1,4,null,null,1,null,200,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (32,9,'Наименование организации','NAME',1,0,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (33,9,'Страна регистрации','COUNTRY',4,1,10,53,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (34,9,'Регистрационный номер организации в стране ее регистрации (инкорпорации)','REG_NUM',1,2,null,null,1,null,80,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (35,9,'Код налогоплательщика в стране регистрации (инкорпорации) или его аналог (если имеется)','TAXPAYER_CODE',1,3,null,null,1,null,80,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (36,9,'Адрес организации','ADDRESS',1,4,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (37,9,'ИНН / КИО','INN_KIO',1,5,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (38,9,'КПП','KPP',2,6,null,null,1,0,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (39,9,'Сведения об организации','ORGANIZATION',4,7,70,641,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (655,9,'Резидент оффшорной зоны','OFFSHORE',4,8,38,249,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (656,9,'Дополнительная  информация','DOP_INFO',1,9,null,null,1,null,250,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (657,9,'Освобождена от налога на прибыль либо является резидентом Сколково','SKOLKOVO',4,10,38,249,1,null,10,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (55,11,'Код услуги','CODE',2,0,null,null,1,0,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (56,11,'Тип услуги','NAME',1,1,null,null,1,null,100,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (57,12,'Код единицы измерения','CODE',1,0,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (58,12,'Наименование единицы измерения','NAME',1,1,null,null,1,null,100,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (59,12,'Условное обозначение','SYMBOL',1,2,null,null,1,null,10,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (60,13,'Код','CODE',2,0,null,null,1,0,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (61,13,'Услуга','NAME',1,1,null,null,1,null,100,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (62,14,'Идентификатор','ID',2,0,null,null,1,0,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (63,14,'Режим переговорной сделки','MODE',1,1,null,null,1,null,10,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (64,15,'Код валюты. Цифровой','CODE',1,0,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (65,15,'Код валюты. Буквенный','CODE_2',1,1,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (66,15,'Наименование валюты','NAME',1,2,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (67,15,'Краткое наименование стран и территорий','COUNTRY_NAMES',1,3,null,null,1,null,500,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (68,16,'Идентификатор','ID',2,0,null,null,1,0,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (69,16,'Код','CODE',1,1,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (70,16,'Тип сделки','TYPE',1,2,null,null,1,null,100,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (40,17,'Внутренний код','INNER_CODE',1,0,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (41,17,'Код ОКП','OKP_CODE',1,1,null,null,1,null,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (42,17,'Наименование','NAME',1,2,null,null,1,null,10,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (43,18,'Код','CODE',2,0,null,null,1,0,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (44,18,'Признак физической поставки','SIGN',1,1,null,null,1,null,10,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (45,20,'Код','CODE',2,0,null,null,1,0,10,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (46,20,'Направление','DIRECTION',1,1,null,null,1,null,10,1);

--INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (47,21,'Код','CODE',2,0,null,null,1,0,10);


INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (80,	22,	'Цифровой код валюты',						'CODE_NUMBER',		4,		0,		15,		66,		1,	null,	3, 0); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (81,	22,	'Курс валюты',								'RATE',				2,		1,		null,	null,	1,	4,		24, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (90,	23,	'Ставка рефинансирования,  %',				'RATE',				2,		0,		null,	null,	1,	2,		19, 0); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (91,	23,	'Нормативный документ',						'DOCUMENT',			1,		1,		null,	null,	1,	null,	255, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (100,	24,	'Код вида платежа',							'CODE',				1,		0,		null,	null,	1,	null,	1, 1); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (101,	24,	'Наименование кода вида платежа',			'NAME',				1,		1,		null,	null,	1,	null,	4000, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (110,	25,	'Код',										'CODE',				2,		0,		null,	null,	1,	0,		1, 1); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (111,	25,	'Значение',									'NAME',				1,		1,		null,	null,	1,	null,	50, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (120,	26,	'Код',										'CODE',				2,		0,		null,	null,	1,	0,		1, 1); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (121,	26,	'Значение',									'NAME',				1,		1,		null,	null,	1,	null,	255, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (130,	27,	'Код налогового учёта ',					'CODE',				1,		0,		null,	null,	1,	null,	5,   0); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (131,	27,	'Группа расхода',							'GROUP_EXP',		1,		1,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (132,	27,	'Вид расхода по операциям',					'TYPE_EXP',			1,		2,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (133,	27,	'Балансовый счёт по учёту расхода',			'BALANCE_ACCOUNT',	1,		3,		null,	null,	1,	null,	13, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (134,	27,	'Символ ОПУ',								'OPU',				1,		4,		null,	null,	1,	null,	13, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (360,	27,	'Номер',									'NUMBER',			1,		5,		null,	null,	1,	null,	12, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (135,	27,	'Нормативный документ(в актуальной редакции)', 'NORMATIVE_DOCUMENT',1,		6,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (136,	27,	'Учётное подразделение Центрального аппарата ОАО «Сбербанк России»', 'UNIT',				1,		7,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (137,	27,	'Первичный документ для налогового учёта', 	'BASIC_DOCUMENT',	1,		8,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (138,	27,	'Форма регистра налогового учёта', 			'FORM',				1,		9,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (139,	27,	'Признак расхода', 							'TYPE',				1,		10,		null,	null,	1,	null,	255, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (140,	28,	'Код налогового учёта ',					'CODE',				1,		0,		null,	null,	1,	null,	5, 0); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (141,	28,	'Группа дохода',							'GROUP_INCOME',		1,		1,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (142,	28,	'Вид доходов по операциям',					'TYPE_INCOME',		1,		2,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (143,	28,	'Балансовый счёт по учёту расхода',			'BALANCE_ACCOUNT',	1,		3,		null,	null,	1,	null,	13, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (144,	28,	'Символ ОПУ',								'OPU',				1,		4,		null,	null,	1,	null,	13, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (350,	28,	'Номер',									'NUMBER',			1,		5,		null,	null,	1,	null,	12, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (145,	28,	'Нормативный документ(в актуальной редакции)', 'NORMATIVE_DOCUMENT',1,		6,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (146,	28,	'Учётное подразделение Центрального аппарата ОАО «Сбербанк России»',  'UNIT',	1,		7,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (147,	28,	'Первичный документ для налогового учёта', 	'BASIC_DOCUMENT',	1,		8,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (148,	28,	'Форма регистра налогового учёта', 			'FORM',				1,		9,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (149,	28,	'Признак дохода', 							'TYPE',				1,		10,		null,	null,	1,	null,	255, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (150,	29,	'КНУ',										'CODE',				1,		0,		null,	null,	1,	null,	10, 0); 
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (151,	29,	'Наименование вида дохода/расхода',			'NAME',				1,		1,		null,	null,	1,	null,	2000, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (152,	29,	'Номер балансового счёта',					'BALANCE_ACCOUNT',	1,		2,		null,	null,	1,	null,	10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (153,	29,	'Символ ОПУ',								'OPU',				1,		3,		null,	null,	1,	null,	10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (154,	29,	'Код РНУ',									'RNU',				1,		4,		null,	null,	1,	null,	3, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (160,	30,	'Код подразделения',							'ID',				2,		0,		null,	null,	1,	0,		15, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (161,	30,	'Наименование подразделения',					'NAME',				1,		1,		null,	null,	1,	null,	255, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (162,	30,	'Сокращенное наименование подразделения',		'SHORTNAME',		1,		2,		null,	null,	1,	null,	255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (163,	30,	'Код родительского подразделения',				'PARENT_ID',	4,		3,		30,		160,		1,	null,	13, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (164,	30,	'Тип подразделения',							'TYPE',				2,		4,		null,	null,	1,	0,		15, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (165,	30,	'Индекс территориального банка',				'TB_INDEX',			1,		5,		null,	null,	1,	null,	2, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (166,	30,	'Код подразделения в нотации Сбербанка',		'SBRF_CODE',		1,		6,		null,	null,	1,	null,	255, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (210,	34,	'Код ОКВЭД',						'CODE',			1,		0,		null,	null,	1,	null,			6, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (211,	34,	'Наименование',						'NAME',			1,		1,		null,	null,	1,	null,		250, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (212,	35,	'Код лица, подписавшего документ',	'CODE',			2,		0,		null,	null,	1,	0,			1, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE,ORD,REFERENCE_ID,ATTRIBUTE_ID,VISIBLE,PRECISION, WIDTH, REQUIRED) VALUES (213,	35,	'Лицо, подписавшее документ',		'NAME',			1,		1,		null,	null,	1,	null,		50, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (170,31,'Идентификатор (первичный ключ)','DEPARTMENT_ID',4,0, 30, 161,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (226,31,'Субъект Российской Федерации (код)','DICT_REGION_ID',4,1,4,9,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (225,31,'Код по ОКАТО','OKATO',4,2,3,7,1,null,11,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (224,31,'ИНН','INN',1,3,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (223,31,'КПП','KPP',1,4,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (222,31,'Код налогового органа','TAX_ORGAN_CODE',1,5,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (216,31,'Код вида экономической деятельности и по классификатору ОКВЭД','OKVED_CODE',4,6,34,210,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (221,31,'Номер контактного телефона','PHONE',1,7,null,null,1,null,20,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (220,31,'Код формы реорганизации и ликвидации','REORG_FORM_CODE',4,8,5,13,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (219,31,'ИНН реорганизованного обособленного подразделения','REORG_INN',1,9,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (218,31,'КПП реорганизованного обособленного подразделения','REORG_KPP',1,10,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (217,31,'Наименование подразделения','NAME',1,11,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (171,31,'Признак лица подписавшего документ','SIGNATORY_ID',4,12,35,212,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (172,31,'Фамилия подписанта','SIGNATORY_SURNAME',1,13,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (173,31,'Имя подписанта','SIGNATORY_FIRSTNAME',1,14,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (174,31,'Отчество подписанта','SIGNATORY_LASTNAME',1,15,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (175,31,'Наименование документа, подтверждающего полномочия представителя','APPROVE_DOC_NAME',1,16,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (176,31,'Наименование организации-представителя налогоплательщика','APPROVE_ORG_NAME',1,17,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (177,31,'Код места, по которому представляется документ','TAX_PLACE_TYPE_CODE',4,18,2,3,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (178,31,'Версия программы, с помощью которой сформирован файл','APP_VERSION',1,19,null,null,1,null,40,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (179,31,'Версия формата','FORMAT_VERSION',1,20,null,null,1,null,10,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (192,33,'Идентификатор (первичный ключ)','DEPARTMENT_ID',4,0, 30, 161,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (237,33,'Субъект Российской Федерации (код)','DICT_REGION_ID',4,1,4,9,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (236,33,'Код по ОКАТО','OKATO',4,2,3,7,1,null,11,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (235,33,'ИНН','INN',1,3,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (234,33,'КПП','KPP',1,4,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (233,33,'Код налогового органа','TAX_ORGAN_CODE',1,5,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (227,33,'Код вида экономической деятельности и по классификатору ОКВЭД','OKVED_CODE',4,6,34,210,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (232,33,'Номер контактного телефона','PHONE',1,7,null,null,1,null,20,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (231,33,'Код формы реорганизации и ликвидации','REORG_FORM_CODE',4,8,5,13,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (230,33,'ИНН реорганизованного обособленного подразделения','REORG_INN',1,9,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (229,33,'КПП реорганизованного обособленного подразделения','REORG_KPP',1,10,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (228,33,'Наименование подразделения','NAME',1,11,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (193,33,'Признак лица подписавшего документ','SIGNATORY_ID',4,12,35,212,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (194,33,'Фамилия подписанта','SIGNATORY_SURNAME',1,13,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (195,33,'Имя подписанта','SIGNATORY_FIRSTNAME',1,14,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (196,33,'Отчество подписанта','SIGNATORY_LASTNAME',1,15,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (197,33,'Наименование документа, подтверждающего полномочия представителя','APPROVE_DOC_NAME',1,16,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (198,33,'Наименование организации-представителя налогоплательщика','APPROVE_ORG_NAME',1,17,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (199,33,'Код места, по которому представляется документ','TAX_PLACE_TYPE_CODE',4,18,2,3,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (200,33,'Ставка налога','TAX_RATE',2,19,null,null,1,2,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (201,33,'Версия программы, с помощью которой сформирован файл','APP_VERSION',1,20,null,null,1,null,40,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (202,33,'Версия формата','FORMAT_VERSION',1,21,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (203,33,'Обязанность по уплате налога','OBLIGATION',4,22,25,110,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (204,33,'Признак расчёта','TYPE',4,23,26,120,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (205,33,'Сумма налога на прибыль, выплаченная за пределами Российской Федерации в отчётном периоде','SUM_TAX',2,24,null,null,1,0,15,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (206,33,'Сумма налога с выплаченных дивидендов за пределами Российской Федерации в последнем квартале отчётного периода','SUM_DIVIDENDS',2,25,null,null,1,0,15,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (214,36,'Идентификатор','ID',2,0,null,null,1,0,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (215,36,'Признак','SIGN',1,1,null,null,1,null,100,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (180,37,'Идентификатор (первичный ключ)','DEPARTMENT_ID',4,0,30,162,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (181,37,'Субъект Российской Федерации (код)','DICT_REGION_ID',4,1,4,9,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (182,37,'Код по ОКАТО','OKATO',4,2,3,7,1,null,11,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (183,37,'ИНН','INN',1,3,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (184,37,'КПП','KPP',1,4,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (185,37,'Код налогового органа','TAX_ORGAN_CODE',1,5,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (186,37,'Код вида экономической деятельности и по классификатору ОКВЭД','OKVED_CODE',4,6,34,210,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (187,37,'Номер контактного телефона','PHONE',1,7,null,null,1,null,20,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (188,37,'Код формы реорганизации и ликвидации','REORG_FORM_CODE',4,8,5,13,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (189,37,'ИНН реорганизованного обособленного подразделения','REORG_INN',1,9,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (190,37,'КПП реорганизованного обособленного подразделения','REORG_KPP',1,10,null,null,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (191,37,'Наименование подразделения','NAME',1,11,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (238,37,'Признак лица подписавшего документ','SIGNATORY_ID',4,12,35,212,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (239,37,'Фамилия подписанта','SIGNATORY_SURNAME',1,13,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (240,37,'Имя подписанта','SIGNATORY_FIRSTNAME',1,14,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (241,37,'Отчество подписанта','SIGNATORY_LASTNAME',1,15,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (242,37,'Наименование документа, подтверждающего полномочия представителя','APPROVE_DOC_NAME',1,16,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (243,37,'Наименование организации-представителя налогоплательщика','APPROVE_ORG_NAME',1,17,null,null,1,null,100,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (244,37,'Код места, по которому представляется документ','TAX_PLACE_TYPE_CODE',4,18,2,3,1,null,10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (245,37,'Версия программы, с помощью которой сформирован файл','APP_VERSION',1,19,null,null,1,null,40,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (246,37,'Версия формата','FORMAT_VERSION',1,20,null,null,1,null,10,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (249,38,'Код','CODE',2,0,null,null,1,0,1,1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (250,38,'Значение','VALUE',1,1,null,null,1,null,3,1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 400, 40,'Код','CODE', 2, 0,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 401, 40,'Наименование','NAME', 1, 1,null,null,1,null, 100, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 410, 41,'Первичный ключ (номер п.п.)','ID', 2, 1,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 411, 41,'Код транспортного средства','CODE', 1, 2,null,null,1,null, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 412, 41,'Срок использования "От", лет','MIN_AGE', 2, 3,null,null,1, 0, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 413, 41,'Срок использования "До", лет','MAX_AGE', 2, 4,null,null,1, 0, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 414, 41,'Мощность "От"','MIN_POWER', 2, 5,null,null,1, 2, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 415, 41,'Мощность "До"','MAX_POWER', 2, 6,null,null,1, 2, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 416, 41,'Ставка, руб.','VALUE', 2, 7,null,null,1, 2, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 417, 41,'Код региона','DICT_REGION_ID', 4, 8, 4, 10 ,1,null, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 418, 41,'Ед. измерения мощности','UNIT_OF_POWER', 4, 9, 12, 58, 1, null, 10, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 420, 42,'Идентификатор записи','ID', 2, 1,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 423, 42,'Наименование','NAME', 1, 4,null,null,1,null, 100, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 421, 42,'Идентификатор родительской записи','PARENT_ID', 4, 2, 42, 423, 1, null, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 422, 42,'Код типа','CODE', 1, 3,null,null,1,null, 10, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 501, 50,'Идентификатор отчетного периода','REPORT_PERIOD_ID', 2, 1,null,null,1, 0, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 502, 50,'Номер счета','ACCOUNT', 1, 2,null,null,1,null, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 510, 50,'Наименование счета','ACCOUNT_NAME', 1, 3,null,null,1,null, 100, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 503, 50,'Входящие остатки по дебету','INCOME_DEBET_REMAINS', 2, 4,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 504, 50,'Входящие остатки по кредиту','INCOME_CREDIT_REMAINS', 2, 5,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 505, 50,'Обороты по дебету','DEBET_RATE', 2, 6,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 506, 50,'Обороты по кредиту','CREDIT_RATE', 2, 7,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 507, 50,'Исходящие остатки по дебету','OUTCOME_DEBET_REMAINS', 2, 8,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 508, 50,'Исходящие остатки по кредиту','OUTCOME_CREDIT_REMAINS', 2, 9,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 509, 50,'Код подразделения','DEPARTMENT_ID', 4, 10,30, 162,1, null, 10, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 520, 52,'Идентификатор отчетного периода','REPORT_PERIOD_ID', 2, 1,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 521, 52,'Код ОПУ','OPU_CODE', 1, 2,null,null,1,null, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 522, 52,'Сумма','TOTAL_SUM', 2, 3,null,null,1, 4, 10, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 524, 52,'Наименование статьи','ITEM_NAME', 1, 5,null,null,1,null, 100, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 525, 52,'Код подразделения','DEPARTMENT_ID', 4, 6,30,162,1, null, 10, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 625, 63,'Код цифровой','CODE', 1, 1, null,null,1, null, 2, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 626, 63,'Код буквенный','STRCODE', 1, 2,null,null,1,null, 3, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 627, 63,'Наименование условия поставки','NAME', 1, 3,null,null,1,null, 500, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 628, 63,'Название географического пункта погрузки/разгрузки','SHIPPING_POINT', 1, 4,null,null,1,null, 500, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 629, 64,'Код','CODE', 2, 1,null,null,1, 0, 3, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 630, 64,'Наименование','NAME', 1, 2,null,null,1,null, 500, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 631, 65,'Код','CODE', 1, 1,null,null,1, null, 3, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 632, 65,'Наименование','NAME', 1, 2,null,null,1,null, 500, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 633, 66,'Код','CODE', 2, 1,null,null,1, 0, 1, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 634, 66,'Наименование','NAME', 1, 2,null,null,1,null, 500, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 635, 67,'Код','CODE', 1, 1,null,null,1, null, 3, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 636, 67,'Наименование','NAME', 1, 2,null,null,1,null, 500, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 637, 68,'Код ОКП','CODE', 1, 1,null,null,1, null, 7, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 638, 68,'Наименование','NAME', 1, 2,null,null,1,null, 130, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 639, 69,'Код','CODE', 2, 1,null,null,1, 0, 1, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 640, 69,'Наименование','NAME', 1, 2,null,null,1,null, 130, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 641, 70,'Код','CODE', 2, 1,null,null,1, 0, 1, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 642, 70,'Значение','VALUE', 1, 2,null,null,1,null, 250, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 643, 71,'Группа','GROUP', 2, 1,null,null,1, 0, 1, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 644, 71,'Интервал согласно ст. 258 НК РФ','INTERVAL', 1, 2,null,null,1,null, 255, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 645, 71,'Срок полезного использования (месяцев)','TERM', 2, 3,null,null,1,0, 3, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 646, 72,'Код ставки','CODE', 1, 1,null,null,1, null, 5, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 647, 72,'Наименование ставки','NAME', 1, 2,null,null,1,null, 255, 1);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 648, 73,'Код','CODE', 2, 1,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 649, 73,'Наименование  позиции','NAME', 1, 2,null,null,1,null, 500, 0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 650, 73,'Код  родительского  элемента','PARENT_CODE', 2, 3,null,null,1, 0, 10, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 651, 74,'Код пользователя','CODE', 2, 1,null,null,1, 0, 9,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 652, 74,'ФИО','NAME', 1, 2,null,null,1,null, 50,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 653, 74,'Код подразделения','DEPARTMENT_ID', 4, 3, 30, 162, 1, null, 10,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 654, 74,'E-mail','EMAIL', 1, 4,null,null,1,null, 128,0);

update ref_book_attribute
set width=10
where width<10 and (ref_book_id>=22 OR ref_book_id<=9);

update ref_book_attribute
set width=100
where width>100 and (ref_book_id>=22 OR ref_book_id<=9);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 601, 60,'Код части сделки','CODE', 2, 1,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 602, 60,'Часть сделки','NAME', 1, 2,null,null,1,null, 100, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 611, 61,'Код сделки','CODE', 2, 1,null,null,1, 0, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 612, 61,'Тип сделки','TYPE', 1, 2,null,null,1,null, 100, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 621, 62,'Код признака','CODE', 1, 1,null,null,1,null, 10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES ( 622, 62,'Признак ценной бумаги','NAME', 1, 2,null,null,1,null, 100,0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (801,80,'Код','CODE',2,0,null,null,1,0,10, 1);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (802,80,'Вид изменения','CHANGE_TYPE',1,1,null,null,1,null,20, 0);

INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (818,85,'Код срочной сделки','CODE',2,1,null,null,1,0,1,0);
INSERT INTO REF_BOOK_ATTRIBUTE (ID, REF_BOOK_ID, NAME, ALIAS, TYPE, ORD, REFERENCE_ID, ATTRIBUTE_ID, VISIBLE, PRECISION, WIDTH, REQUIRED) VALUES (819,85,'Вид срочной сделки','CONTRACT_TYPE',1,2,null,null,1,null,255,0);
