INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (1, 'Воздушные транспортные средства', NULL, 40100);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (2, 'Воздушные суда', 1, 41000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (3, 'Самолеты', 1, 41100);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (4, 'Самолеты пассажирские и грузовые', 1, 41110);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (5, 'самолеты пассажирские', 4, 41112);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (6, 'самолеты грузовые', 4, 41113);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (7, 'Самолеты прочие', 1, 41120);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (8, 'самолеты пожарные', 7, 41121);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (9, 'самолеты аварийно-технической службы', 7, 41122);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (10, 'самолеты санитарной авиации и медицинской службы', 7, 41123);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (11, 'другие самолеты', 7, 41124);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (12, 'Вертолеты', 1, 41200);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (13, 'Вертолеты пассажирские и грузовые', 1, 41210);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (14, 'вертолеты пассажирские', 13, 41212);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (15, 'вертолеты грузовые', 13, 41213);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (16, 'Вертолеты прочие', 1, 41220);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (17, 'вертолеты пожарные', 16, 41221);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (18, 'вертолеты аварийно-технической службы', 16, 41222);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (19, 'другие вертолеты', 16, 41224);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (20, 'Воздушные транспортные средства, не имеющие двигателей', 1, 41300);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (21, 'Воздушные транспортные средства, для которых определяется тяга реактивного двигателя', 1, 41400);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (22, 'Другие воздушные транспортные средства', 1, 41900);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (23, 'иные воздушные суда, имеющие двигатели', 22, 41901);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (24, 'Водные транспортные средства', NULL, 40200);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (25, 'Суда морские и внутреннего плавания', 24, 42000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (26, 'Суда пассажирские и грузовые морские и речные самоходные (кроме включенных по коду 42100)', 24, 42010);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (27, 'суда пассажирские морские и речные (кроме включенных по коду 42100)', 26, 42012);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (28, 'суда грузовые морские и речные самоходные (кроме включенных по коду 42100)', 26, 42013);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (29, 'Суда промысловые морские и речные', 24, 42020);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (30, 'суда промысловые морские и речные самоходные', 29, 42021);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (31, 'суда промысловые морские и речные несамоходные', 29, 42022);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (32, 'Суда спортивные, туристские и прогулочные', 24, 42030);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (33, 'весельные лодки, а также моторные лодки с двигателем мощностью не свыше 5 лошадиных сил', 32, 42031);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (34, 'спортивные, туристские и прогулочные суда самоходные (кроме включенных по кодам 42200, 42300 - 42600)', 32, 42032);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (35, 'спортивные, туристские и прогулочные суда несамоходные', 32, 42033);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (36, 'Теплоходы', 24, 42100);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (37, 'Яхты', 24, 42200);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (38, 'Катера', 24, 42300);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (39, 'Гидроциклы', 24, 42400);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (40, 'Моторные лодки', 24, 42500);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (41, 'Парусно-моторные суда', 24, 42600);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (42, 'Несамоходные (буксируемые) суда', 24, 42700);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (43, 'суда пассажирские и грузовые морские и речные несамоходные', 42, 42701);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (44, 'Водные транспортные средства, не имеющие двигателей (кроме весельных лодок)', 24, 42800);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (45, 'Другие водные транспортные средства', 24, 42900);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (46, 'Другие водные транспортные средства самоходные', 24, 42910);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (47, 'пожарные суда', 46, 42911);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (48, 'суда аварийно-технической службы', 46, 42912);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (49, 'суда медицинской службы', 46, 42913);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (50, 'прочие водные транспортные средства', 46, 42914);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (51, 'Другие водные транспортные средства несамоходные', 24, 42920);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (52, 'другие водные транспортные средства несамоходные, для которых определяется валовая вместимость', 51, 42921);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (53, 'прочие водные транспортные средства несамоходные', 51, 42922);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (54, 'Наземные транспортные средства', NULL, 50000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (55, 'Автомобили легковые', 54, 51000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (56, 'Автомобили легковые, специально оборудованные для использования инвалидами', 55, 51001);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (57, 'Автомобили легковые с мощностью двигателя до 100 лошадиных сил (до 73,55 кВт), полученные (приобретенные) через органы социальной защиты населения в установленном законом порядке', 55, 51002);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (58, 'Автомобили легковые медицинской службы', 55, 51003);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (59, 'Прочие автомобили легковые (кроме включённых по кодам 56600, 56700)', 55, 51004);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (60, 'Автомобили грузовые', 54, 52000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (61, 'Автомобили грузовые (кроме включённых по коду 57000)', 60, 52001);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (62, 'Тракторы, комбайны и специальные автомашины', 54, 53000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (63, 'Тракторы сельскохозяйственные', 62, 53001);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (64, 'Тракторы прочие', 62, 53002);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (65, 'Самоходные комбайны', 62, 53003);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (66, 'Специальные автомашины (кроме включённых по коду 59015)', 62, 53004);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (67, 'Прочие тракторы, комбайны и специальные машины', 62, 53005);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (68, 'Автобусы', 54, 54000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (69, 'Автобусы медицинской службы', 68, 54001);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (70, 'Автобусы городского и междугороднего транспорта', 68, 54002);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (71, 'Прочие автобусы', 68, 54003);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (72, 'Мототранспортные средства', 54, 56000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (73, 'Мотоциклы', 54, 56100);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (74, 'Мотороллеры', 54, 56200);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (75, 'Мотосани', 54, 56600);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (76, 'Снегоходы', 54, 56700);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (77, 'Прочие самоходные транспортные средства, машины и механизмы на пневматическом и гусеничном ходу', 54, 57000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (78, 'Самоходные машины и механизмы на пневматическом и гусеничном ходу (кроме включённых по кодам 53001 - 53005)', 77, 57001);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (79, 'Иные автотранспортные средства', 54, 59000);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (80, 'Автомобили специальные', 54, 59010);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (81, 'Автомобили пожарные', 80, 59011);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (82, 'Автомашины для очистки и уборки городов', 80, 59012);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (83, 'Автомашины аварийно-технической службы', 80, 59013);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (84, 'Автомобили-фургоны медицинской службы', 80, 59014);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (85, 'Специальные автомашины (молоковозы, скотовозы, специальные машины для перевозки птицы, машины для перевозки минеральных удобрений, ветеринарной помощи, технического обслуживания)', 80, 59015);
INSERT into transport_type_code (ID, NAME, PARENT_ID, CODE) VALUES (86, 'Прочие специальные автомобили, на шасси которых установлено различное оборудование, агрегаты и установки', 80, 59016);
