INSERT INTO event (id,name) VALUES (1,'Создать');
INSERT INTO event (id,name) VALUES (12,'После создания');
INSERT INTO event (id,name) VALUES (2,'Удалить');
INSERT INTO event (id,name) VALUES (3,'Рассчитать');
INSERT INTO event (id,name) VALUES (4,'Обобщить');
INSERT INTO event (id,name) VALUES (5,'Проверить');
INSERT INTO event (id,name) VALUES (6,'Сохранить');
INSERT INTO event (id,name) VALUES (7,'Импорт данных');
INSERT INTO event (id,name) VALUES (8,'Получение данных');
INSERT INTO event (id,name) VALUES (9,'Получение защищенных данных');
INSERT INTO event (id,name) VALUES (10,'Тестирование скриптов');
INSERT INTO event (id,name) VALUES (11,'Миграция из АС "Ведение РНУ"');
INSERT INTO event (id,name) VALUES (101,'Утвердить из "Создана"');
INSERT INTO event (id,name) VALUES (102,'Вернуть из "Утверждена" в "Создана"');
INSERT INTO event (id,name) VALUES (103,'Принять из "Утверждена"');
INSERT INTO event (id,name) VALUES (104,'Вернуть из "Принята" в "Утверждена"');
INSERT INTO event (id,name) VALUES (105,'Принять из "Создана"');
INSERT INTO event (id,name) VALUES (106,'Вернуть из "Принята" в "Создана"');
INSERT INTO event (id,name) VALUES (107,'Подготовить из "Создана"');
INSERT INTO event (id,name) VALUES (108,'Вернуть из "Подготовлена" в "Создана"');
INSERT INTO event (id,name) VALUES (109,'Принять из "Подготовлена"');
INSERT INTO event (id,name) VALUES (110,'Вернуть из "Принята" в "Подготовлена"');
INSERT INTO event (id,name) VALUES (111,'Утвердить из "Подготовлена"');
INSERT INTO event (id,name) VALUES (112,'Вернуть из "Утверждена" в "Подготовлена"');
INSERT INTO event (id,name) VALUES (203,'После принять из "Утверждена"');
INSERT INTO event (id,name) VALUES (204,'После вернуть из "Принята" в "Утверждена"');
INSERT INTO event (id,name) VALUES (205,'После принять из "Создана"');
INSERT INTO event (id,name) VALUES (206,'После вернуть из "Принята" в "Создана"');
INSERT INTO event (id,name) VALUES (207,'После принять из "Подготовлена"');
INSERT INTO event (id,name) VALUES (208,'После вернуть из "Принята" в "Подготовлена"');
INSERT INTO event (id,name) VALUES (209,'После утвердить из "Подготовлена"');
INSERT INTO event (id,name) VALUES (210,'После вернуть "Подготовлена" из "Утверждена"');
INSERT INTO event (id,name) VALUES (301,'Добавить строку');
INSERT INTO event (id,name) VALUES (303,'Удалить строку');
INSERT INTO event (id,name) VALUES (302,'Загрузка');
INSERT INTO event (id,name) VALUES (401,'Импорт из транспортных файлов');
INSERT INTO event (id,name) VALUES (402,'Загрузка транспортных файлов в каталог загрузки');
INSERT INTO event (id,name) VALUES (501,'Вход пользователя в Систему');
INSERT INTO event (id,name) VALUES (502,'Выход пользователя из Системы');
INSERT INTO event (id,name) VALUES (503,'Взаимодействие с внешней АС');
INSERT INTO event (id,name) VALUES (601,'Архивирование журнала событий');
INSERT INTO event (id,name) VALUES (701,'Версия создана');
INSERT INTO event (id,name) VALUES (702,'Версия изменена');
INSERT INTO event (id,name) VALUES (703,'Версия введена в действие');
INSERT INTO event (id,name) VALUES (704,'Версия выведена из действия');
INSERT INTO event (id,name) VALUES (705,'Версия удалена');
INSERT INTO event (id,name) VALUES (650,'Отправка email');
INSERT INTO event (id,name) VALUES (801,'Вход пользователя в модуль');
INSERT INTO event (id,name) VALUES (802,'Выход пользователя из модуля');
INSERT INTO event (id,name) VALUES (810,'Загрузка данных о договорах обеспечения');
INSERT INTO event (id,name) VALUES (811,'Загрузка данных о клиентах');
INSERT INTO event (id,name) VALUES (812,'Загрузка данных о платежах');
INSERT INTO event (id,name) VALUES (813,'Загрузка справочника');
INSERT INTO event (id,name) VALUES (820,'Создание анкеты клиента');
INSERT INTO event (id,name) VALUES (821,'Редактирование анкеты клиента');
INSERT INTO event (id,name) VALUES (830,'Создание договора гарантии');
INSERT INTO event (id,name) VALUES (831,'Редактирование договора гарантии');
INSERT INTO event (id,name) VALUES (832,'Закрытие договора гарантии');
INSERT INTO event (id,name) VALUES (840,'Создание договора обеспечения');
INSERT INTO event (id,name) VALUES (841,'Редактирование договора обеспечения');
INSERT INTO event (id,name) VALUES (842,'Закрытие договора обеспечения');
INSERT INTO event (id,name) VALUES (850,'Создание задачи формирования РНУ-23');
INSERT INTO event (id,name) VALUES (860,'Создание задачи формирования отчета');
INSERT INTO event (id,name) VALUES (901,'Создание подразделения');
INSERT INTO event (id,name) VALUES (902,'Модификация подразделения');
INSERT INTO event (id,name) VALUES (903,'Удаление подразделения');
INSERT INTO event (id,name) VALUES (904,'Импорт скриптов');
INSERT INTO event (id,name) VALUES (951,'Редактирование конфигурационного параметра');