--Заполнение признаков 01-14
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1530' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1531' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1533' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1535' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1536' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1537' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1539' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1541' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1542' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1543' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1544' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1545' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1546' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1547' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1548' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1549' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1551' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1552' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1554' and status=0 order by version desc) where rownum=1),'01','Начисление дохода при выводе денежных средств с брокерского счёта');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1530' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1531' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1533' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1535' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1536' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1537' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1539' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1541' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1542' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1543' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1544' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1545' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1546' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1547' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1548' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1549' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1551' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1552' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1554' and status=0 order by version desc) where rownum=1),'02','Начисление дохода при выводе ценных бумаг с торгового раздела счёта депо');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1530' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1531' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1533' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1535' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1536' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1537' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1539' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1541' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1542' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1543' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1544' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1545' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1546' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1547' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1548' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1549' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1551' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1552' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1554' and status=0 order by version desc) where rownum=1),'03','Начисление дохода при расторжении договора брокерского обслуживания');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1530' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1531' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1533' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1535' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1536' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1537' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1539' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1541' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='1542' and status=0 order by version desc) where rownum=1),'04','Начисление дохода по окончанию налогового периода за который начислен доход');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2000' and status=0 order by version desc) where rownum=1),'05','Заработная плата');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2000' and status=0 order by version desc) where rownum=1),'06','Заработная плата при увольнении');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2002' and status=0 order by version desc) where rownum=1),'07','Разовая премия');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2002' and status=0 order by version desc) where rownum=1),'08','Ежемесячная премия');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2002' and status=0 order by version desc) where rownum=1),'09','Ежеквартальная премия');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2002' and status=0 order by version desc) where rownum=1),'10','Премия по итогам года');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2000' and status=0 order by version desc) where rownum=1),'11','Возмещение командировочных расходов');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2000' and status=0 order by version desc) where rownum=1),'12','Доплата до среднего заработка за время нахождения работника в командировке');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2740' and status=0 order by version desc) where rownum=1),'13','Выплата дохода в денежной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2750' and status=0 order by version desc) where rownum=1),'13','Выплата дохода в денежной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2790' and status=0 order by version desc) where rownum=1),'13','Выплата дохода в денежной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='4800' and status=0 order by version desc) where rownum=1),'13','Выплата дохода в денежной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2520' and status=0 order by version desc) where rownum=1),'14','Выплата дохода в натуральной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2720' and status=0 order by version desc) where rownum=1),'14','Выплата дохода в натуральной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2740' and status=0 order by version desc) where rownum=1),'14','Выплата дохода в натуральной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2750' and status=0 order by version desc) where rownum=1),'14','Выплата дохода в натуральной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='2790' and status=0 order by version desc) where rownum=1),'14','Выплата дохода в натуральной форме');
insert into ref_book_income_kind(id,income_type_id,mark,name) values(seq_ref_book_record.nextval,(select id from (select id,version from ref_book_income_type where code='4800' and status=0 order by version desc) where rownum=1),'14','Выплата дохода в натуральной форме');

--заполняем оставшиеся
insert into ref_book_income_kind(id,income_type_id,mark,name)
select seq_ref_book_record.nextval,r.id,'00','-'
  from ref_book_income_type r
 where not exists (select 1 from ref_book_income_kind k where k.income_type_id=r.id)
   and r.status=0
   and r.version=(select max(version) from ref_book_income_type v where v.code=r.code);

