
package com.aplana.sbrf.taxaccounting.web.module.sudir.ws.departmentendpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TaxAccountingSupportingData", targetNamespace = "http://taxaccounting.sbt.ru/SupportingData/")
public interface TaxAccountingSupportingData {


    /**
     * 
     * @return
     *     returns java.util.List<ru.sbt.taxaccounting.supportingdata.TaxAccDepartment>
     */
    @WebMethod(action = "http://taxaccounting.sbt.ru/SupportingData/getDepartments")
    @WebResult(name = "department", targetNamespace = "http://taxaccounting.sbt.ru/SupportingData/getDepartments")
    @RequestWrapper(localName = "getDepartments", targetNamespace = "http://taxaccounting.sbt.ru/SupportingData/", className = "ru.sbt.taxaccounting.supportingdata.GetDepartments")
    @ResponseWrapper(localName = "getDepartmentsResponse", targetNamespace = "http://taxaccounting.sbt.ru/SupportingData/", className = "ru.sbt.taxaccounting.supportingdata.GetDepartmentsResponse")
    public List<TaxAccDepartment> getDepartments();

}
