
package com.aplana.sbrf.taxaccounting.web.module.sudir.ws.accountendpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GenericAccountManagement", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
public interface GenericAccountManagement {


    /**
     * 
     * @param accountId
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.ResetPasswordResponse")
    public void resetPassword(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountId
     * @param password
     * @return
     *     returns boolean
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @WebResult(name = "validatePasswordReturn", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
    @RequestWrapper(localName = "validatePassword", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.ValidatePassword")
    @ResponseWrapper(localName = "validatePasswordResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.ValidatePasswordResponse")
    public boolean validatePassword(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId,
        @WebParam(name = "password", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String password)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountId
     * @param password
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setPassword", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.SetPassword")
    @ResponseWrapper(localName = "setPasswordResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.SetPasswordResponse")
    public void setPassword(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId,
        @WebParam(name = "password", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String password)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountId
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "suspendAccount", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.SuspendAccount")
    @ResponseWrapper(localName = "suspendAccountResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.SuspendAccountResponse")
    public void suspendAccount(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountInfo
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.CreateAccountResponse")
    public void createAccount(
        @WebParam(name = "accountInfo", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        GenericAccountInfo accountInfo)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountInfo
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyAccount", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.ModifyAccount")
    @ResponseWrapper(localName = "modifyAccountResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.ModifyAccountResponse")
    public void modifyAccount(
        @WebParam(name = "accountInfo", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        GenericAccountInfo accountInfo)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountId
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "restoreAccount", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.RestoreAccount")
    @ResponseWrapper(localName = "restoreAccountResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.RestoreAccountResponse")
    public void restoreAccount(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountId
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAccount", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.DeleteAccount")
    @ResponseWrapper(localName = "deleteAccountResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.DeleteAccountResponse")
    public void deleteAccount(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId)
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GenericAccountInfo>
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @WebResult(name = "getAccountListReturn", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
    @RequestWrapper(localName = "getAccountList", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GetAccountList")
    @ResponseWrapper(localName = "getAccountListResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GetAccountListResponse")
    public List<GenericAccountInfo> getAccountList()
        throws GenericAccountManagementException_Exception
    ;

    /**
     * 
     * @param accountId
     * @return
     *     returns java.util.List<ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GenericAccountInfo>
     * @throws GenericAccountManagementException_Exception
     */
    @WebMethod
    @WebResult(name = "getAccountListByIdReturn", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
    @RequestWrapper(localName = "getAccountListById", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GetAccountListById")
    @ResponseWrapper(localName = "getAccountListByIdResponse", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0", className = "ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GetAccountListByIdResponse")
    public List<GenericAccountInfo> getAccountListById(
        @WebParam(name = "accountId", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
        String accountId)
        throws GenericAccountManagementException_Exception
    ;

}
