
package com.aplana.sbrf.taxaccounting.web.module.sudir.ws.accountendpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://sberbank.ru/soa/service/sudir/itdi/smallsystem.generic.webservice.connector/1.0.0")
public class GenericAccountManagementException_Exception
    extends Exception
{

	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GenericAccountManagementException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GenericAccountManagementException_Exception(String message, GenericAccountManagementException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GenericAccountManagementException_Exception(String message, GenericAccountManagementException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.sberbank.soa.service.sudir.itdi.smallsystem_generic_webservice_connector._1_0.GenericAccountManagementException
     */
    public GenericAccountManagementException getFaultInfo() {
        return faultInfo;
    }

}
