--alter session set current_schema=ndfl_1_0;
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(1,1,to_date('01.01.2016','dd.mm.yyyy'),0,'01','Республика Адыгея','79','79');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(2,2,to_date('01.01.2016','dd.mm.yyyy'),0,'02','Республика Башкортостан','80','80');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(3,3,to_date('01.01.2016','dd.mm.yyyy'),0,'03','Республика Бурятия','81','81');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(4,4,to_date('01.01.2016','dd.mm.yyyy'),0,'04','Республика Алтай','84','84');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(5,5,to_date('01.01.2016','dd.mm.yyyy'),0,'05','Республика Дагестан','82','82');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(6,6,to_date('01.01.2016','dd.mm.yyyy'),0,'06','Ингушская Республика','26','26');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(7,7,to_date('01.01.2016','dd.mm.yyyy'),0,'07','Кабардино - Балкарская Республика','83','83');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(8,8,to_date('01.01.2016','dd.mm.yyyy'),0,'08','Республика Калмыкия','85','85');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(9,9,to_date('01.01.2016','dd.mm.yyyy'),0,'09','Карачаево - Черкесская Республика','91','91');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(10,10,to_date('01.01.2016','dd.mm.yyyy'),0,'10','Республика Карелия','86','86');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(11,11,to_date('01.01.2016','dd.mm.yyyy'),0,'11','Республика Коми','87','87');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(12,12,to_date('01.01.2016','dd.mm.yyyy'),0,'12','Республика Марий Эл','88','88');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(13,13,to_date('01.01.2016','dd.mm.yyyy'),0,'13','Республика Мордовия','89','89');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(14,14,to_date('01.01.2016','dd.mm.yyyy'),0,'14','Республика Саха (Якутия)','98','98');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(15,15,to_date('01.01.2016','dd.mm.yyyy'),0,'15','Республика Северная Осетия','90','90');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(16,16,to_date('01.01.2016','dd.mm.yyyy'),0,'16','Республика Татарстан (Татарстан)','92','92');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(17,17,to_date('01.01.2016','dd.mm.yyyy'),0,'17','Республика Тува','93','93');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(18,18,to_date('01.01.2016','dd.mm.yyyy'),0,'18','Удмуртская Республика','94','94');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(19,19,to_date('01.01.2016','dd.mm.yyyy'),0,'19','Республика Хакасия','95','95');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(20,20,to_date('01.01.2016','dd.mm.yyyy'),0,'20','Чеченская Республика','96','96');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(21,21,to_date('01.01.2016','dd.mm.yyyy'),0,'21','Чувашская Республика- Чаваш Республики','97','97');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(22,22,to_date('01.01.2016','dd.mm.yyyy'),0,'22','Алтайский край','01','01');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(23,23,to_date('01.01.2016','dd.mm.yyyy'),0,'23','Краснодарский край','03','03');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(24,24,to_date('01.01.2016','dd.mm.yyyy'),0,'24','Красноярский край','04','04');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(25,25,to_date('01.01.2016','dd.mm.yyyy'),0,'25','Приморский край','05','05');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(26,26,to_date('01.01.2016','dd.mm.yyyy'),0,'26','Ставропольский край','07','07');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(27,27,to_date('01.01.2016','dd.mm.yyyy'),0,'27','Хабаровский край','08','08');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(28,28,to_date('01.01.2016','dd.mm.yyyy'),0,'28','Амурская область','10','10');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(29,29,to_date('01.01.2016','dd.mm.yyyy'),0,'29','Архангельская область','11','11');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(30,30,to_date('01.01.2016','dd.mm.yyyy'),0,'30','Астраханская область','12','12');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(31,31,to_date('01.01.2016','dd.mm.yyyy'),0,'31','Белгородская область','14','14');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(32,32,to_date('01.01.2016','dd.mm.yyyy'),0,'32','Брянская область','15','15');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(33,33,to_date('01.01.2016','dd.mm.yyyy'),0,'33','Владимирская область','17','17');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(34,34,to_date('01.01.2016','dd.mm.yyyy'),0,'34','Волгоградская область','18','18');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(35,35,to_date('01.01.2016','dd.mm.yyyy'),0,'35','Вологодская область','19','19');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(36,36,to_date('01.01.2016','dd.mm.yyyy'),0,'36','Воронежская область','20','20');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(37,37,to_date('01.01.2016','dd.mm.yyyy'),0,'37','Ивановская область','24','24');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(38,38,to_date('01.01.2016','dd.mm.yyyy'),0,'38','Иркутская область','25','25');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(39,39,to_date('01.01.2016','dd.mm.yyyy'),0,'39','Калининградская область','27','27');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(40,40,to_date('01.01.2016','dd.mm.yyyy'),0,'40','Калужская область','29','29');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(41,41,to_date('01.01.2016','dd.mm.yyyy'),0,'41','Камчатская область','30','30');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(42,42,to_date('01.01.2016','dd.mm.yyyy'),0,'42','Кемеровская область','32','32');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(43,43,to_date('01.01.2016','dd.mm.yyyy'),0,'43','Кировская область','33','33');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(44,44,to_date('01.01.2016','dd.mm.yyyy'),0,'44','Костромская область','34','34');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(45,45,to_date('01.01.2016','dd.mm.yyyy'),0,'45','Курганская область','37','37');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(46,46,to_date('01.01.2016','dd.mm.yyyy'),0,'46','Курская область','38','38');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(47,47,to_date('01.01.2016','dd.mm.yyyy'),0,'47','Ленинградская область','41','41');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(48,48,to_date('01.01.2016','dd.mm.yyyy'),0,'48','Липецкая область','42','42');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(49,49,to_date('01.01.2016','dd.mm.yyyy'),0,'49','Магаданская область','44','44');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(50,50,to_date('01.01.2016','dd.mm.yyyy'),0,'50','Московская область','46','46');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(51,51,to_date('01.01.2016','dd.mm.yyyy'),0,'51','Мурманская область','47','47');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(52,52,to_date('01.01.2016','dd.mm.yyyy'),0,'52','Нижегородская область','22','22');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(53,53,to_date('01.01.2016','dd.mm.yyyy'),0,'53','Новгородская область','49','49');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(54,54,to_date('01.01.2016','dd.mm.yyyy'),0,'54','Новосибирская область','50','50');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(55,55,to_date('01.01.2016','dd.mm.yyyy'),0,'55','Омская область','52','52');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(56,56,to_date('01.01.2016','dd.mm.yyyy'),0,'56','Оренбургская область','53','53');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(57,57,to_date('01.01.2016','dd.mm.yyyy'),0,'57','Орловская область','54','54');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(58,58,to_date('01.01.2016','dd.mm.yyyy'),0,'58','Пензенская область','56','56');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(59,59,to_date('01.01.2016','dd.mm.yyyy'),0,'59','Пермская область','57','57');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(60,60,to_date('01.01.2016','dd.mm.yyyy'),0,'60','Псковская область','58','58');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(61,61,to_date('01.01.2016','dd.mm.yyyy'),0,'61','Ростовская область','60','60');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(62,62,to_date('01.01.2016','dd.mm.yyyy'),0,'62','Рязанская область','61','61');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(63,63,to_date('01.01.2016','dd.mm.yyyy'),0,'63','Самарская область','36','36');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(64,64,to_date('01.01.2016','dd.mm.yyyy'),0,'64','Саратовская область','63','63');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(65,65,to_date('01.01.2016','dd.mm.yyyy'),0,'65','Сахалинская область','64','64');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(66,66,to_date('01.01.2016','dd.mm.yyyy'),0,'66','Свердловская область','65','65');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(67,67,to_date('01.01.2016','dd.mm.yyyy'),0,'67','Смоленская область','66','66');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(68,68,to_date('01.01.2016','dd.mm.yyyy'),0,'68','Тамбовская область','68','68');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(69,69,to_date('01.01.2016','dd.mm.yyyy'),0,'69','Тверская область','28','28');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(70,70,to_date('01.01.2016','dd.mm.yyyy'),0,'70','Томская область','69','69');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(71,71,to_date('01.01.2016','dd.mm.yyyy'),0,'71','Тульская область','70','70');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(72,72,to_date('01.01.2016','dd.mm.yyyy'),0,'72','Тюменская область','71','71');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(73,73,to_date('01.01.2016','dd.mm.yyyy'),0,'73','Ульяновская область','73','73');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(74,74,to_date('01.01.2016','dd.mm.yyyy'),0,'74','Челябинская область','75','75');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(75,75,to_date('01.01.2016','dd.mm.yyyy'),0,'75','Читинская область','76','76');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(76,76,to_date('01.01.2016','dd.mm.yyyy'),0,'76','Ярославская область','78','78');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(77,77,to_date('01.01.2016','dd.mm.yyyy'),0,'77','г. Москва','45','45');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(78,78,to_date('01.01.2016','dd.mm.yyyy'),0,'78','г. Санкт-Петербург','40','40');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(79,79,to_date('01.01.2016','dd.mm.yyyy'),0,'79','Еврейская автономная область','99','99');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(80,80,to_date('01.01.2016','dd.mm.yyyy'),0,'83','Ненецкий автономный округ','1110','118');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(81,81,to_date('01.01.2016','dd.mm.yyyy'),0,'86','Ханты - Мансийский автономный округ','','718');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(82,82,to_date('01.01.2016','dd.mm.yyyy'),0,'87','Чукотский автономный округ','77','77');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(83,83,to_date('01.01.2016','dd.mm.yyyy'),0,'89','Ямало - Ненецкий автономный округ','','719');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(85,85,to_date('01.01.2016','dd.mm.yyyy'),0,'91','Республика Крым','35','35');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(86,86,to_date('01.01.2016','dd.mm.yyyy'),0,'92','г. Севастополь','67','67');
insert into ref_book_region(id,record_id,version,status,code,name,okato_definition,oktmo_definition) values(84,84,to_date('01.01.2016','dd.mm.yyyy'),0,'99','Иные территории, включая город и космодром Байконур',null,null);

