insert into ref_book_okved(id,record_id,version,status,code,name) values(0,0,to_date('01.01.2016','dd.mm.yyyy'),0,'65','Финансовое посредничество');
insert into ref_book_okved(id,record_id,version,status,code,name) values(1,1,to_date('01.01.2016','dd.mm.yyyy'),0,'65.1','Денежное посредничество');
insert into ref_book_okved(id,record_id,version,status,code,name) values(2,2,to_date('01.01.2016','dd.mm.yyyy'),0,'65.11','Деятельность Центрального банка Российской Федерации');
insert into ref_book_okved(id,record_id,version,status,code,name) values(3,3,to_date('01.01.2016','dd.mm.yyyy'),0,'65.11.1','Разработка и проведение единой государственной денежно-кредитной политики');
insert into ref_book_okved(id,record_id,version,status,code,name) values(4,4,to_date('01.01.2016','dd.mm.yyyy'),0,'65.11.11','Регулирование налично-денежного обращения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(5,5,to_date('01.01.2016','dd.mm.yyyy'),0,'65.11.12','Организация системы рефинансирования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(6,6,to_date('01.01.2016','dd.mm.yyyy'),0,'65.11.9','Прочая деятельность Центрального банка Российской Федерации');
insert into ref_book_okved(id,record_id,version,status,code,name) values(7,7,to_date('01.01.2016','dd.mm.yyyy'),0,'65.12','Прочее денежное посредничество');
insert into ref_book_okved(id,record_id,version,status,code,name) values(8,8,to_date('01.01.2016','dd.mm.yyyy'),0,'65.2','Прочее финансовое посредничество');
insert into ref_book_okved(id,record_id,version,status,code,name) values(9,9,to_date('01.01.2016','dd.mm.yyyy'),0,'65.21','Финансовый лизинг');
insert into ref_book_okved(id,record_id,version,status,code,name) values(10,10,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22','Предоставление кредита');
insert into ref_book_okved(id,record_id,version,status,code,name) values(11,11,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22.1','Предоставление потребительского кредита');
insert into ref_book_okved(id,record_id,version,status,code,name) values(12,12,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22.2','Предоставление займов промышленности');
insert into ref_book_okved(id,record_id,version,status,code,name) values(13,13,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22.3','Предоставление денежных ссуд под залог недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(14,14,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22.4','Предоставление кредитов на покупку домов специализированными учреждениями, не принимающими депозиты');
insert into ref_book_okved(id,record_id,version,status,code,name) values(15,15,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22.5','Предоставление услуг по обеспечению кредитных карточек');
insert into ref_book_okved(id,record_id,version,status,code,name) values(16,16,to_date('01.01.2016','dd.mm.yyyy'),0,'65.22.6','Предоставление ломбардами краткосрочных кредитов под залог движимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(17,17,to_date('01.01.2016','dd.mm.yyyy'),0,'65.23','Финансовое посредничество, не включенное в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(18,18,to_date('01.01.2016','dd.mm.yyyy'),0,'65.23.1','Капиталовложения в ценные бумаги');
insert into ref_book_okved(id,record_id,version,status,code,name) values(19,19,to_date('01.01.2016','dd.mm.yyyy'),0,'65.23.2','Деятельность дилеров');
insert into ref_book_okved(id,record_id,version,status,code,name) values(20,20,to_date('01.01.2016','dd.mm.yyyy'),0,'65.23.3','Капиталовложения в собственность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(21,21,to_date('01.01.2016','dd.mm.yyyy'),0,'65.23.4','Заключение свопов, опционов и других биржевых сделок');
insert into ref_book_okved(id,record_id,version,status,code,name) values(22,22,to_date('01.01.2016','dd.mm.yyyy'),0,'65.23.5','Деятельность холдинг-компаний в области финансового посредничества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(23,23,to_date('01.01.2016','dd.mm.yyyy'),0,'66','Страхование');
insert into ref_book_okved(id,record_id,version,status,code,name) values(24,24,to_date('01.01.2016','dd.mm.yyyy'),0,'66.0','Страхование');
insert into ref_book_okved(id,record_id,version,status,code,name) values(25,25,to_date('01.01.2016','dd.mm.yyyy'),0,'66.01','Страхование жизни и накопление');
insert into ref_book_okved(id,record_id,version,status,code,name) values(26,26,to_date('01.01.2016','dd.mm.yyyy'),0,'66.02','Негосударственное пенсионное обеспечение');
insert into ref_book_okved(id,record_id,version,status,code,name) values(27,27,to_date('01.01.2016','dd.mm.yyyy'),0,'66.02.1','Деятельность по негосударственному пенсионному обеспечению');
insert into ref_book_okved(id,record_id,version,status,code,name) values(28,28,to_date('01.01.2016','dd.mm.yyyy'),0,'66.02.2','Страхование ренты');
insert into ref_book_okved(id,record_id,version,status,code,name) values(29,29,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03','Прочие виды страхования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(30,30,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03.1','Дополнительное медицинское страхование');
insert into ref_book_okved(id,record_id,version,status,code,name) values(31,31,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03.2','Имущественное страхование');
insert into ref_book_okved(id,record_id,version,status,code,name) values(32,32,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03.3','Страхование ответственности');
insert into ref_book_okved(id,record_id,version,status,code,name) values(33,33,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03.4','Страхование от несчастных случаев и болезней');
insert into ref_book_okved(id,record_id,version,status,code,name) values(34,34,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03.5','Страхование финансовых рисков');
insert into ref_book_okved(id,record_id,version,status,code,name) values(35,35,to_date('01.01.2016','dd.mm.yyyy'),0,'66.03.9','Прочие виды страхования, не включенные в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(36,36,to_date('01.01.2016','dd.mm.yyyy'),0,'67','Вспомогательная деятельность в сфере финансового посредничества и страхования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(37,37,to_date('01.01.2016','dd.mm.yyyy'),0,'67.1','Вспомогательная деятельность в сфере финансового посредничества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(38,38,to_date('01.01.2016','dd.mm.yyyy'),0,'67.11','Управление финансовыми рынками');
insert into ref_book_okved(id,record_id,version,status,code,name) values(39,39,to_date('01.01.2016','dd.mm.yyyy'),0,'67.11.1','Деятельность фондовых, товарных, валютных и валютно-фондовых бирж');
insert into ref_book_okved(id,record_id,version,status,code,name) values(40,40,to_date('01.01.2016','dd.mm.yyyy'),0,'67.11.11','Деятельность по организации торговли на финансовых рынках');
insert into ref_book_okved(id,record_id,version,status,code,name) values(41,41,to_date('01.01.2016','dd.mm.yyyy'),0,'67.11.12','Деятельность по ведению реестра владельцев ценных бумаг (деятельность регистраторов)');
insert into ref_book_okved(id,record_id,version,status,code,name) values(42,42,to_date('01.01.2016','dd.mm.yyyy'),0,'67.11.13','Деятельность по обеспечению эффективности функционирования финансовых рынков');
insert into ref_book_okved(id,record_id,version,status,code,name) values(43,43,to_date('01.01.2016','dd.mm.yyyy'),0,'67.11.19','Прочая деятельность, связанная с управлением финансовыми рынками, не включенная в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(44,44,to_date('01.01.2016','dd.mm.yyyy'),0,'67.12','Биржевые операции с фондовыми ценностями');
insert into ref_book_okved(id,record_id,version,status,code,name) values(45,45,to_date('01.01.2016','dd.mm.yyyy'),0,'67.12.1','Брокерская деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(46,46,to_date('01.01.2016','dd.mm.yyyy'),0,'67.12.2','Деятельность по управлению ценными бумагами');
insert into ref_book_okved(id,record_id,version,status,code,name) values(47,47,to_date('01.01.2016','dd.mm.yyyy'),0,'67.12.3','Деятельность по определению взаимных обязательств (клиринг)');
insert into ref_book_okved(id,record_id,version,status,code,name) values(48,48,to_date('01.01.2016','dd.mm.yyyy'),0,'67.12.4','Эмиссионная деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(49,49,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13','Прочая вспомогательная деятельность в сфере финансового посредничества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(50,50,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13.1','Предоставление брокерских услуг по ипотечным операциям');
insert into ref_book_okved(id,record_id,version,status,code,name) values(51,51,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13.2','Предоставление услуг пунктами по обмену валют');
insert into ref_book_okved(id,record_id,version,status,code,name) values(52,52,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13.3','Предоставление услуг по упаковыванию денег');
insert into ref_book_okved(id,record_id,version,status,code,name) values(53,53,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13.4','Консультирование по вопросам финансового посредничества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(54,54,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13.5','Предоставление услуг по хранению ценностей');
insert into ref_book_okved(id,record_id,version,status,code,name) values(55,55,to_date('01.01.2016','dd.mm.yyyy'),0,'67.13.51','Депозитарная деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(56,56,to_date('01.01.2016','dd.mm.yyyy'),0,'67.2','Вспомогательная деятельность в сфере страхования и негосударственного пенсионного обеспечения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(57,57,to_date('01.01.2016','dd.mm.yyyy'),0,'67.20','Вспомогательная деятельность в сфере страхования и негосударственного пенсионного обеспечения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(58,58,to_date('01.01.2016','dd.mm.yyyy'),0,'67.20.1','Деятельность страховых агентов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(59,59,to_date('01.01.2016','dd.mm.yyyy'),0,'67.20.2','Деятельность специалистов по оценке страхового риска и убытков');
insert into ref_book_okved(id,record_id,version,status,code,name) values(60,60,to_date('01.01.2016','dd.mm.yyyy'),0,'67.20.3','Деятельность специалистов по расчетам оценки страховой вероятности (актуариев)');
insert into ref_book_okved(id,record_id,version,status,code,name) values(61,61,to_date('01.01.2016','dd.mm.yyyy'),0,'67.20.4','Деятельность распорядителей спасательными работами');
insert into ref_book_okved(id,record_id,version,status,code,name) values(62,62,to_date('01.01.2016','dd.mm.yyyy'),0,'67.20.9','Прочая вспомогательная деятельность в сфере страхования, кроме обязательного социального обеспечения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(63,63,to_date('01.01.2016','dd.mm.yyyy'),0,'70.1','Подготовка к продаже, покупка и продажа собственного недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(64,64,to_date('01.01.2016','dd.mm.yyyy'),0,'70.11','Подготовка к продаже собственного недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(65,65,to_date('01.01.2016','dd.mm.yyyy'),0,'70.11.1','Подготовка к продаже собственного жилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(66,66,to_date('01.01.2016','dd.mm.yyyy'),0,'70.11.2','Подготовка к продаже собственного нежилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(67,67,to_date('01.01.2016','dd.mm.yyyy'),0,'70.12','Покупка и продажа собственного недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(68,68,to_date('01.01.2016','dd.mm.yyyy'),0,'70.12.1','Покупка и продажа собственного жилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(69,69,to_date('01.01.2016','dd.mm.yyyy'),0,'70.12.2','Покупка и продажа собственных нежилых зданий и помещений');
insert into ref_book_okved(id,record_id,version,status,code,name) values(70,70,to_date('01.01.2016','dd.mm.yyyy'),0,'70.12.3','Покупка и продажа земельных участков');
insert into ref_book_okved(id,record_id,version,status,code,name) values(71,71,to_date('01.01.2016','dd.mm.yyyy'),0,'70.2','Сдача внаем собственного недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(72,72,to_date('01.01.2016','dd.mm.yyyy'),0,'70.20','Сдача внаем собственного недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(73,73,to_date('01.01.2016','dd.mm.yyyy'),0,'70.20.1','Сдача внаем собственного жилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(74,74,to_date('01.01.2016','dd.mm.yyyy'),0,'70.20.2','Сдача внаем собственного нежилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(75,75,to_date('01.01.2016','dd.mm.yyyy'),0,'70.3','Предоставление посреднических услуг, связанных с недвижимым имуществом');
insert into ref_book_okved(id,record_id,version,status,code,name) values(76,76,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31','Деятельность агентств по операциям с недвижимым имуществом');
insert into ref_book_okved(id,record_id,version,status,code,name) values(77,77,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31.1','Предоставление посреднических услуг при покупке, продаже и аренде недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(78,78,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31.11','Предоставление посреднических услуг при покупке, продаже и аренде жилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(79,79,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31.12','Предоставление посреднических услуг при покупке, продаже и аренде нежилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(80,80,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31.2','Предоставление посреднических услуг при оценке недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(81,81,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31.21','Предоставление посреднических услуг при оценке жилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(82,82,to_date('01.01.2016','dd.mm.yyyy'),0,'70.31.22','Предоставление посреднических услуг при оценке нежилого недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(83,83,to_date('01.01.2016','dd.mm.yyyy'),0,'70.32','Управление недвижимым имуществом');
insert into ref_book_okved(id,record_id,version,status,code,name) values(84,84,to_date('01.01.2016','dd.mm.yyyy'),0,'70.32.1','Управление эксплуатацией жилого фонда');
insert into ref_book_okved(id,record_id,version,status,code,name) values(85,85,to_date('01.01.2016','dd.mm.yyyy'),0,'70.32.2','Управление эксплуатацией нежилого фонда');
insert into ref_book_okved(id,record_id,version,status,code,name) values(86,86,to_date('01.01.2016','dd.mm.yyyy'),0,'70.32.3','Деятельность по учету и технической инвентаризации недвижимого имущества');
insert into ref_book_okved(id,record_id,version,status,code,name) values(87,87,to_date('01.01.2016','dd.mm.yyyy'),0,'72.1','Консультирование по аппаратным средствам вычислительной техники');
insert into ref_book_okved(id,record_id,version,status,code,name) values(88,88,to_date('01.01.2016','dd.mm.yyyy'),0,'72.10','Консультирование по аппаратным средствам вычислительной техники');
insert into ref_book_okved(id,record_id,version,status,code,name) values(89,89,to_date('01.01.2016','dd.mm.yyyy'),0,'72.2','Разработка программного обеспечения и консультирование в этой области');
insert into ref_book_okved(id,record_id,version,status,code,name) values(90,90,to_date('01.01.2016','dd.mm.yyyy'),0,'72.20','Разработка программного обеспечения и консультирование в этой области');
insert into ref_book_okved(id,record_id,version,status,code,name) values(91,91,to_date('01.01.2016','dd.mm.yyyy'),0,'72.3','Обработка данных');
insert into ref_book_okved(id,record_id,version,status,code,name) values(92,92,to_date('01.01.2016','dd.mm.yyyy'),0,'72.30','Обработка данных');
insert into ref_book_okved(id,record_id,version,status,code,name) values(93,93,to_date('01.01.2016','dd.mm.yyyy'),0,'72.4','Деятельность по созданию и использованию баз данных и информационных ресурсов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(94,94,to_date('01.01.2016','dd.mm.yyyy'),0,'72.40','Деятельность по созданию и использованию баз данных и информационных ресурсов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(95,95,to_date('01.01.2016','dd.mm.yyyy'),0,'72.5','Техническое обслуживание и ремонт офисных машин и вычислительной техники');
insert into ref_book_okved(id,record_id,version,status,code,name) values(96,96,to_date('01.01.2016','dd.mm.yyyy'),0,'72.50','Техническое обслуживание и ремонт офисных машин и вычислительной техники');
insert into ref_book_okved(id,record_id,version,status,code,name) values(97,97,to_date('01.01.2016','dd.mm.yyyy'),0,'72.6','Прочая деятельность, связанная с использованием вычислительной техники и информационных технологий');
insert into ref_book_okved(id,record_id,version,status,code,name) values(98,98,to_date('01.01.2016','dd.mm.yyyy'),0,'72.60','Прочая деятельность, связанная с использованием вычислительной техники и информационных технологий');
insert into ref_book_okved(id,record_id,version,status,code,name) values(99,99,to_date('01.01.2016','dd.mm.yyyy'),0,'70','Операции с недвижимым имуществом');
insert into ref_book_okved(id,record_id,version,status,code,name) values(100,100,to_date('01.01.2016','dd.mm.yyyy'),0,'71','Аренда машин и оборудования без оператора; прокат бытовых изделий и предметов личного пользования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(101,101,to_date('01.01.2016','dd.mm.yyyy'),0,'71.1','Аренда легковых автомобилей');
insert into ref_book_okved(id,record_id,version,status,code,name) values(102,102,to_date('01.01.2016','dd.mm.yyyy'),0,'71.10','Аренда легковых автомобилей');
insert into ref_book_okved(id,record_id,version,status,code,name) values(103,103,to_date('01.01.2016','dd.mm.yyyy'),0,'71.2','Аренда прочих транспортных средств и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(104,104,to_date('01.01.2016','dd.mm.yyyy'),0,'71.21','Аренда прочих сухопутных транспортных средств и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(105,105,to_date('01.01.2016','dd.mm.yyyy'),0,'71.21.1','Аренда прочего автомобильного транспорта и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(106,106,to_date('01.01.2016','dd.mm.yyyy'),0,'71.21.2','Аренда железнодорожного транспорта и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(107,107,to_date('01.01.2016','dd.mm.yyyy'),0,'71.22','Аренда водных транспортных средств и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(108,108,to_date('01.01.2016','dd.mm.yyyy'),0,'71.23','Аренда воздушных транспортных средств и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(109,109,to_date('01.01.2016','dd.mm.yyyy'),0,'71.3','Аренда прочих машин и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(110,110,to_date('01.01.2016','dd.mm.yyyy'),0,'71.31','Аренда сельскохозяйственных машин и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(111,111,to_date('01.01.2016','dd.mm.yyyy'),0,'71.32','Аренда строительных машин и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(112,112,to_date('01.01.2016','dd.mm.yyyy'),0,'71.33','Аренда офисных машин и оборудования, включая вычислительную технику');
insert into ref_book_okved(id,record_id,version,status,code,name) values(113,113,to_date('01.01.2016','dd.mm.yyyy'),0,'71.33.1','Аренда офисных машин и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(114,114,to_date('01.01.2016','dd.mm.yyyy'),0,'71.33.2','Аренда вычислительных машин и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(115,115,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34','Аренда прочих машин и оборудования, не включенных в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(116,116,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.1','Аренда двигателей, турбин и станков');
insert into ref_book_okved(id,record_id,version,status,code,name) values(117,117,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.2','Аренда горного и нефтепромыслового оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(118,118,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.3','Аренда подъемно-транспортного оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(119,119,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.4','Аренда профессиональной радио- и телевизионной аппаратуры и аппаратуры связи');
insert into ref_book_okved(id,record_id,version,status,code,name) values(120,120,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.5','Аренда контрольно-измерительной аппаратуры');
insert into ref_book_okved(id,record_id,version,status,code,name) values(121,121,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.6','Аренда медицинской техники');
insert into ref_book_okved(id,record_id,version,status,code,name) values(122,122,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.7','Аренда торгового оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(123,123,to_date('01.01.2016','dd.mm.yyyy'),0,'71.34.9','Аренда прочих машин и оборудования научного и промышленного назначения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(124,124,to_date('01.01.2016','dd.mm.yyyy'),0,'71.4','Прокат бытовых изделий и предметов личного пользования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(125,125,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40','Прокат бытовых изделий и предметов личного пользования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(126,126,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.1','Прокат телевизоров, радиоприемников, устройств видеозаписи, аудиозаписи и подобного оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(127,127,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.2','Прокат аудио- и видеокассет, грампластинок и записей на других технических носителях информации');
insert into ref_book_okved(id,record_id,version,status,code,name) values(128,128,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.3','Прокат мебели, электрических и неэлектрических бытовых приборов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(129,129,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.4','Прокат инвентаря и оборудования для проведения досуга и отдыха');
insert into ref_book_okved(id,record_id,version,status,code,name) values(130,130,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.5','Прокат музыкальных инструментов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(131,131,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.6','Прокат предметов медицинского и санитарного обслуживания');
insert into ref_book_okved(id,record_id,version,status,code,name) values(132,132,to_date('01.01.2016','dd.mm.yyyy'),0,'71.40.9','Прокат прочих бытовых изделий и предметов личного пользования для домашних хозяйств, предприятий и организаций, не включенных в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(133,133,to_date('01.01.2016','dd.mm.yyyy'),0,'72','Деятельность, связанная с использованием вычислительной техники и информационных технологий');
insert into ref_book_okved(id,record_id,version,status,code,name) values(134,134,to_date('01.01.2016','dd.mm.yyyy'),0,'73','Научные исследования и разработки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(135,135,to_date('01.01.2016','dd.mm.yyyy'),0,'73.1','Научные исследования и разработки в области естественных и технических наук');
insert into ref_book_okved(id,record_id,version,status,code,name) values(136,136,to_date('01.01.2016','dd.mm.yyyy'),0,'73.10','Научные исследования и разработки в области естественных и технических наук');
insert into ref_book_okved(id,record_id,version,status,code,name) values(137,137,to_date('01.01.2016','dd.mm.yyyy'),0,'73.2','Научные исследования и разработки в области общественных и гуманитарных наук');
insert into ref_book_okved(id,record_id,version,status,code,name) values(138,138,to_date('01.01.2016','dd.mm.yyyy'),0,'73.20','Научные исследования и разработки в области общественных и гуманитарных наук');
insert into ref_book_okved(id,record_id,version,status,code,name) values(139,139,to_date('01.01.2016','dd.mm.yyyy'),0,'74','Предоставление прочих видов услуг');
insert into ref_book_okved(id,record_id,version,status,code,name) values(140,140,to_date('01.01.2016','dd.mm.yyyy'),0,'74.1','Деятельность в области права, бухгалтерского учета и аудита; консультирование по вопросам коммерческой деятельности и управления предприятием');
insert into ref_book_okved(id,record_id,version,status,code,name) values(141,141,to_date('01.01.2016','dd.mm.yyyy'),0,'74.11','Деятельность в области права');
insert into ref_book_okved(id,record_id,version,status,code,name) values(142,142,to_date('01.01.2016','dd.mm.yyyy'),0,'74.12','Деятельность в области бухгалтерского учета и аудита');
insert into ref_book_okved(id,record_id,version,status,code,name) values(143,143,to_date('01.01.2016','dd.mm.yyyy'),0,'74.12.1','Деятельность в области бухгалтерского учета');
insert into ref_book_okved(id,record_id,version,status,code,name) values(144,144,to_date('01.01.2016','dd.mm.yyyy'),0,'74.12.2','Аудиторская деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(145,145,to_date('01.01.2016','dd.mm.yyyy'),0,'74.13','Исследование конъюнктуры рынка и выявление общественного мнения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(146,146,to_date('01.01.2016','dd.mm.yyyy'),0,'74.13.1','Исследование конъюнктуры рынка');
insert into ref_book_okved(id,record_id,version,status,code,name) values(147,147,to_date('01.01.2016','dd.mm.yyyy'),0,'74.13.2','Деятельность по изучению общественного мнения');
insert into ref_book_okved(id,record_id,version,status,code,name) values(148,148,to_date('01.01.2016','dd.mm.yyyy'),0,'74.14','Консультирование по вопросам коммерческой деятельности и управления');
insert into ref_book_okved(id,record_id,version,status,code,name) values(149,149,to_date('01.01.2016','dd.mm.yyyy'),0,'74.15','Деятельность по управлению финансово-промышленными группами и холдинг-компаниями');
insert into ref_book_okved(id,record_id,version,status,code,name) values(150,150,to_date('01.01.2016','dd.mm.yyyy'),0,'74.15.1','Деятельность по управлению финансово-промышленными группами');
insert into ref_book_okved(id,record_id,version,status,code,name) values(151,151,to_date('01.01.2016','dd.mm.yyyy'),0,'74.15.2','Деятельность по управлению холдинг-компаниями');
insert into ref_book_okved(id,record_id,version,status,code,name) values(152,152,to_date('01.01.2016','dd.mm.yyyy'),0,'74.2','Деятельность в области архитектуры; инженерно-техническое проектирование; геолого-разведочные и геофизические работы; геодезическая и картографическая деятельность; деятельность в области стандартизации и метрологии; деятельность в области гидрометеорологии и смежных с ней областях; виды деятельности, связанные с решением технических задач, не включенные в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(153,153,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20','Деятельность в области архитектуры; инженерно-техническое проектирование; геолого-разведочные и геофизические работы; геодезическая и картографическая деятельность; деятельность в области стандартизации и метрологии; деятельность в области гидрометеорологии и смежных с ней областях; виды деятельности, связанные с решением технических задач, не включенные в другие группировки');
insert into ref_book_okved(id,record_id,version,status,code,name) values(154,154,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.1','Деятельность в области архитектуры, инженерно-техническое проектирование в промышленности и строительстве');
insert into ref_book_okved(id,record_id,version,status,code,name) values(155,155,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.11','Архитектурная деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(156,156,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.12','Проектирование производственных помещений, включая размещение машин и оборудования, промышленный дизайн');
insert into ref_book_okved(id,record_id,version,status,code,name) values(157,157,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.13','Проектирование, связанное со строительством инженерных сооружений, включая гидротехнические сооружения; проектирование движения транспортных потоков');
insert into ref_book_okved(id,record_id,version,status,code,name) values(158,158,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.14','Разработка проектов промышленных процессов и производств, относящихся к электротехнике, электронной технике, горному делу, химической технологии, машиностроению, а также в области промышленного строительства, системотехники и техники безопасности');
insert into ref_book_okved(id,record_id,version,status,code,name) values(159,159,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.15','Разработка проектов в области кондиционирования воздуха, холодильной техники, санитарной техники и мониторинга загрязнения окружающей среды, строительной акустики и т.п.');
insert into ref_book_okved(id,record_id,version,status,code,name) values(160,160,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.2','Геолого-разведочные, геофизические и геохимические работы в области изучения недр');
insert into ref_book_okved(id,record_id,version,status,code,name) values(161,161,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.3','Геодезическая и картографическая деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(162,162,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.31','Топографо-геодезическая деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(163,163,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.32','Картографическая деятельность, включая деятельность в области наименований географических объектов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(164,164,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.33','Гидрографические изыскательские работы');
insert into ref_book_okved(id,record_id,version,status,code,name) values(165,165,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.34','Деятельность, связанная с подготовкой картографической и космической информации, включая аэросъемку');
insert into ref_book_okved(id,record_id,version,status,code,name) values(166,166,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.35','Инженерные изыскания для строительства');
insert into ref_book_okved(id,record_id,version,status,code,name) values(167,167,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.36','Землеустройство');
insert into ref_book_okved(id,record_id,version,status,code,name) values(168,168,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.4','Деятельность в области стандартизации и метрологии');
insert into ref_book_okved(id,record_id,version,status,code,name) values(169,169,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.41','Деятельность в области стандартизации');
insert into ref_book_okved(id,record_id,version,status,code,name) values(170,170,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.42','Деятельность в области метрологии');
insert into ref_book_okved(id,record_id,version,status,code,name) values(171,171,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.44','Деятельность в области аккредитации');
insert into ref_book_okved(id,record_id,version,status,code,name) values(172,172,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.45','Государственный контроль и надзор за стандартами, средствами измерений и обязательной сертификацией');
insert into ref_book_okved(id,record_id,version,status,code,name) values(173,173,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.5','Деятельность в области гидрометеорологии и смежных с ней областях');
insert into ref_book_okved(id,record_id,version,status,code,name) values(174,174,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.51','Океанографические работы');
insert into ref_book_okved(id,record_id,version,status,code,name) values(175,175,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.52','Гелиогеофизические работы');
insert into ref_book_okved(id,record_id,version,status,code,name) values(176,176,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.53','Работы по активному воздействию на гидрометеорологические и геофизические процессы и явления');
insert into ref_book_okved(id,record_id,version,status,code,name) values(177,177,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.54','Работы по метеорологии, климатологии, гидрологии');
insert into ref_book_okved(id,record_id,version,status,code,name) values(178,178,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.55','Работы по мониторингу состояния и загрязнения окружающей природной среды');
insert into ref_book_okved(id,record_id,version,status,code,name) values(179,179,to_date('01.01.2016','dd.mm.yyyy'),0,'74.20.56','Предоставление информации о состоянии и загрязнении окружающей природной среды');
insert into ref_book_okved(id,record_id,version,status,code,name) values(180,180,to_date('01.01.2016','dd.mm.yyyy'),0,'74.3','Технические испытания, исследования и сертификация');
insert into ref_book_okved(id,record_id,version,status,code,name) values(181,181,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30','Технические испытания, исследования и сертификация');
insert into ref_book_okved(id,record_id,version,status,code,name) values(182,182,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.1','Испытания и анализ состава и чистоты материалов и веществ: анализ химических и биологических свойств материалов и веществ (воздуха, воды, бытовых и производственных отходов, топлива, металла, почвы, химических веществ)');
insert into ref_book_okved(id,record_id,version,status,code,name) values(183,183,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.2','Контроль качества пищевых продуктов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(184,184,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.3','Испытания и анализ в научных областях (микробиологии, биохимии, бактериологии и др.)');
insert into ref_book_okved(id,record_id,version,status,code,name) values(185,185,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.4','Испытания и анализ физических свойств материалов и веществ: испытания и анализ физических свойств (прочности, пластичности, электропроводности, радиоактивности) материалов (металлов, пластмасс, тканей, дерева, стекла, бетона и др.); испытания на растяжение, твердость, сопротивление, усталость и высокотемпературный эффект');
insert into ref_book_okved(id,record_id,version,status,code,name) values(186,186,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.5','Испытания и анализ механических и электрических характеристик готовой продукции: моторов, автомобилей, станков, радиоэлектронных устройств, оборудования связи и другого оборудования, включающего механические и электрические компоненты');
insert into ref_book_okved(id,record_id,version,status,code,name) values(187,187,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.6','Испытания и расчеты строительных элементов');
insert into ref_book_okved(id,record_id,version,status,code,name) values(188,188,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.7','Технический контроль автомобилей: периодический технический осмотр легковых и грузовых автомобилей, мотоциклов, автобусов и других автотранспортных средств');
insert into ref_book_okved(id,record_id,version,status,code,name) values(189,189,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.8','Сертификация продукции и услуг');
insert into ref_book_okved(id,record_id,version,status,code,name) values(190,190,to_date('01.01.2016','dd.mm.yyyy'),0,'74.30.9','Прочая деятельность по техническому контролю, испытаниям и анализу');
insert into ref_book_okved(id,record_id,version,status,code,name) values(191,191,to_date('01.01.2016','dd.mm.yyyy'),0,'74.4','Рекламная деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(192,192,to_date('01.01.2016','dd.mm.yyyy'),0,'74.40','Рекламная деятельность');
insert into ref_book_okved(id,record_id,version,status,code,name) values(193,193,to_date('01.01.2016','dd.mm.yyyy'),0,'74.5','Найм рабочей силы и подбор персонала');
insert into ref_book_okved(id,record_id,version,status,code,name) values(194,194,to_date('01.01.2016','dd.mm.yyyy'),0,'74.50','Найм рабочей силы и подбор персонала');
insert into ref_book_okved(id,record_id,version,status,code,name) values(195,195,to_date('01.01.2016','dd.mm.yyyy'),0,'74.50.1','Предоставление услуг по найму рабочей силы');
insert into ref_book_okved(id,record_id,version,status,code,name) values(196,196,to_date('01.01.2016','dd.mm.yyyy'),0,'74.50.2','Предоставление услуг по подбору персонала');
insert into ref_book_okved(id,record_id,version,status,code,name) values(197,197,to_date('01.01.2016','dd.mm.yyyy'),0,'74.6','Проведение расследований и обеспечение безопасности');
insert into ref_book_okved(id,record_id,version,status,code,name) values(198,198,to_date('01.01.2016','dd.mm.yyyy'),0,'74.60','Проведение расследований и обеспечение безопасности');
insert into ref_book_okved(id,record_id,version,status,code,name) values(199,199,to_date('01.01.2016','dd.mm.yyyy'),0,'74.60.1','Оценка уязвимости объектов транспортной инфраструктуры и транспортных средств от актов незаконного вмешательства');
insert into ref_book_okved(id,record_id,version,status,code,name) values(200,200,to_date('01.01.2016','dd.mm.yyyy'),0,'74.60.2','Проведение расследований и обеспечение безопасности, кроме оценки уязвимости объектов транспортной инфраструктуры и транспортных средств от актов незаконного вмешательства');
insert into ref_book_okved(id,record_id,version,status,code,name) values(201,201,to_date('01.01.2016','dd.mm.yyyy'),0,'74.7','Чистка и уборка производственных и жилых помещений, оборудования и транспортных средств');
insert into ref_book_okved(id,record_id,version,status,code,name) values(202,202,to_date('01.01.2016','dd.mm.yyyy'),0,'74.70','Чистка и уборка производственных и жилых помещений, оборудования и транспортных средств');
insert into ref_book_okved(id,record_id,version,status,code,name) values(203,203,to_date('01.01.2016','dd.mm.yyyy'),0,'74.70.1','Чистка и уборка производственных и жилых помещений и оборудования');
insert into ref_book_okved(id,record_id,version,status,code,name) values(204,204,to_date('01.01.2016','dd.mm.yyyy'),0,'74.70.2','Чистка и уборка транспортных средств');
insert into ref_book_okved(id,record_id,version,status,code,name) values(205,205,to_date('01.01.2016','dd.mm.yyyy'),0,'74.70.3','Деятельность по проведению дезинфекционных, дезинсекционных и дератизационных работ');
insert into ref_book_okved(id,record_id,version,status,code,name) values(206,206,to_date('01.01.2016','dd.mm.yyyy'),0,'74.8','Предоставление различных видов услуг');
insert into ref_book_okved(id,record_id,version,status,code,name) values(207,207,to_date('01.01.2016','dd.mm.yyyy'),0,'74.81','Деятельность в области фотографии');
insert into ref_book_okved(id,record_id,version,status,code,name) values(208,208,to_date('01.01.2016','dd.mm.yyyy'),0,'74.82','Упаковывание');
insert into ref_book_okved(id,record_id,version,status,code,name) values(209,209,to_date('01.01.2016','dd.mm.yyyy'),0,'74.83','Предоставление секретарских, редакторских услуг и услуг по переводу');
insert into ref_book_okved(id,record_id,version,status,code,name) values(210,210,to_date('01.01.2016','dd.mm.yyyy'),0,'74.84','Предоставление прочих услуг');