insert into ref_book_fond (id,record_id,version,status,department_id,inn) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select id from department where code='999993'),null);
insert into ref_book_fond (id,record_id,version,status,department_id,inn) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select id from department where code='999994'),null);
insert into ref_book_fond (id,record_id,version,status,department_id,inn) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select id from department where code='999991'),null);
insert into ref_book_fond (id,record_id,version,status,department_id,inn) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select id from department where shortname='УНП'),'7707083893');
insert into ref_book_fond (id,record_id,version,status,department_id,inn) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select id from department where code='999992'),null);
--insert into ref_book_fond (id,record_id,version,status,department_id,inn) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select id from department where code='4'),'7707083893');

insert into ref_book_fond_detail (id,record_id,version,status,ref_book_fond_id,row_ord,department_id,tax_organ_code,kpp,tax_organ_code_mid,present_place,name,okved,region,oktmo,phone,obligation,type,reorg_form_code,reorg_inn,reorg_kpp,signatory_id,signatory_surname,signatory_firstname,signatory_lastname,approve_doc_name,approve_org_name) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select f.id from ref_book_fond f join department d on (d.id=f.department_id) where d.code='999994'),1,(select id from department where code='999994'),'7801','780145001',null,(select id from ref_book_present_place where code='214'),'РЦСВОНУиФО Тестовое',(select id from ref_book_okved where code='65.12'),null,(select id from ref_book_oktmo where code='40300000' and version=to_date('01.01.2014','dd.mm.yyyy')),null,null,null,(select id from ref_book_reorganization where code='6'),null,null,null,null,null,null,null,null);
insert into ref_book_fond_detail (id,record_id,version,status,ref_book_fond_id,row_ord,department_id,tax_organ_code,kpp,tax_organ_code_mid,present_place,name,okved,region,oktmo,phone,obligation,type,reorg_form_code,reorg_inn,reorg_kpp,signatory_id,signatory_surname,signatory_firstname,signatory_lastname,approve_doc_name,approve_org_name) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select f.id from ref_book_fond f join department d on (d.id=f.department_id) where d.code='999991'),1,(select id from department where code='999991'),'7736','773645309',null,(select id from ref_book_present_place where code='214'),'РЦСВОНУиФО ПЦП ОЦ г. Москва',(select id from ref_book_okved where code='65.12'),null,(select id from ref_book_oktmo where code='45393000' and version=to_date('01.01.2014','dd.mm.yyyy')),null,null,null,null,null,null,null,null,null,null,null,null);
insert into ref_book_fond_detail (id,record_id,version,status,ref_book_fond_id,row_ord,department_id,tax_organ_code,kpp,tax_organ_code_mid,present_place,name,okved,region,oktmo,phone,obligation,type,reorg_form_code,reorg_inn,reorg_kpp,signatory_id,signatory_surname,signatory_firstname,signatory_lastname,approve_doc_name,approve_org_name) values (seq_ref_book_record.nextval,seq_ref_book_record_row_id.nextval,to_date('01.01.2017','dd.mm.yyyy'),0,(select f.id from ref_book_fond f join department d on (d.id=f.department_id) where d.shortname='УНП'),1,(select id from department where shortname='УНП'),'1234','0200AZ564','33',(select id from ref_book_present_place where code='222'),null,(select id from ref_book_okved where code='71.3'),(select id from ref_book_region where code='12'),(select id from ref_book_oktmo where code='01601413' and version=to_date('01.01.2014','dd.mm.yyyy')),null,null,null,(select id from ref_book_reorganization where code='1'),null,null,(select id from ref_book_signatory_mark where code='2'),null,null,null,null,null);
