insert into configuration_email(id,name,value,description) values(1,'mail.smtp.user',null,'Имя учетной записи');
insert into configuration_email(id,name,value,description) values(2,'mail.smtp.password',null,'Пароль');
insert into configuration_email(id,name,value,description) values(3,'mail.smtp.host',null,'Адрес сервера SMTP');
insert into configuration_email(id,name,value,description) values(4,'mail.smtp.port',null,'Порт сервера SMTP. Значение по умолчанию: 25.');
insert into configuration_email(id,name,value,description) values(5,'mail.smtp.connectiontimeout',null,'Таймаут соединения. Значение по умолчанию: бесконечность.');
insert into configuration_email(id,name,value,description) values(6,'mail.smtp.timeout',null,'Таймаут чтения. Значение по умолчанию: бесконечность.');
insert into configuration_email(id,name,value,description) values(7,'mail.smtp.writetimeout',null,'Таймаут записи. Значение по умолчанию: бесконечность.');
insert into configuration_email(id,name,value,description) values(8,'mail.smtp.from',null,'Email-адрес отправителя. Может не указываться');
insert into configuration_email(id,name,value,description) values(9,'mail.smtp.localhost',null,'Имя локального узла, используемого в командах SMTP HELO или EHLO.');
insert into configuration_email(id,name,value,description) values(10,'mail.smtp.localaddress',null,'Адрес локального узла, назначенного при выполнении соединения SMTP.');
insert into configuration_email(id,name,value,description) values(11,'mail.smtp.localport',null,'Порт локального узла, назначенного при выполнении соединения SMTP.');
insert into configuration_email(id,name,value,description) values(12,'mail.smtp.ehlo',null,'Если выбрано значение false, то не выполняется авторизация при исполнении команды SMTP EHLO.');
insert into configuration_email(id,name,value,description) values(13,'mail.smtp.auth',null,'Если выбрано значение true, то авторизация пользователей выполняется при помощи команды AUTH. Значение по умолчанию: false');
insert into configuration_email(id,name,value,description) values(14,'mail.smtp.auth.mechanisms',null,'Список, определяющий перечень и очередность использования механизмов аутентификации.');
insert into configuration_email(id,name,value,description) values(15,'mail.smtp.auth.login.disable',null,'Если выбрано значение true, то исключает использование команды AUTH LOGIN. Значение по умолчанию: false');
insert into configuration_email(id,name,value,description) values(16,'mail.smtp.auth.plain.disable',null,'Если выбрано значение true, то исключает использование команды AUTH PLAIN. Значение по умолчанию: false');
insert into configuration_email(id,name,value,description) values(17,'mail.smtp.auth.digest-md5.disable',null,'Если выбрано значение true, то исключает использование команды DIGEST-MD5. Значение по умолчанию: false');
insert into configuration_email(id,name,value,description) values(18,'mail.smtp.auth.ntlm.disable',null,'Если выбрано значение true, то исключает использование команды AUTH NTLM. Значение по умолчанию: false');
insert into configuration_email(id,name,value,description) values(19,'mail.smtp.auth.ntlm.domain',null,'Домен аутентификации NTLM.');
insert into configuration_email(id,name,value,description) values(20,'mail.smtp.auth.ntlm.flags',null,'Параметры протокола NTLM');
insert into configuration_email(id,name,value,description) values(21,'mail.smtp.submitter',null,'Отправитель, используемый в теге AUTH  команды MAIL FROM.');
insert into configuration_email(id,name,value,description) values(22,'mail.smtp.dsn.notify',null,'Параметр NOTIFY для команды RCPT');
insert into configuration_email(id,name,value,description) values(23,'mail.smtp.dsn.ret',null,'Параметр RET для команды MAIL');
insert into configuration_email(id,name,value,description) values(24,'mail.smtp.allow8bitmime',null,'Если выбрано значение true, то включает расширение 8BITMIME на почтовом сервере.');
insert into configuration_email(id,name,value,description) values(25,'mail.smtp.sendpartial',null,'Если указано значение true, то в том случае, если часть адресов получателей указано неверно, сообщение будет отправлено. Если указано значение false, то в том случае, если хотя бы один адрес получателей указано неверно, сообщение не будет отправлено');
insert into configuration_email(id,name,value,description) values(26,'mail.smtp.sasl.enable',null,'Если указано значение true, используется SASL при авторизации. Значение по умолчанию: 0');
insert into configuration_email(id,name,value,description) values(27,'mail.smtp.sasl.mechanisms',null,'Список названий SASL механизмов в порядке проверки использования');
insert into configuration_email(id,name,value,description) values(28,'mail.smtp.sasl.authorizationid',null,'ID, используемый в случае использования SASL при авторизации.');
insert into configuration_email(id,name,value,description) values(29,'mail.smtp.sasl.realm',null,'Область, используемая при аутентификации DIGEST-MD5');
insert into configuration_email(id,name,value,description) values(30,'mail.smtp.sasl.usecanonicalhostname',null,'Если указано значение true, используется для обработки InetAddress.getCanonicalHostName при использовании SASL.');
insert into configuration_email(id,name,value,description) values(31,'mail.smtp.quitwait',null,'Если указано значение true, при выполнении команды QUIT соединение немедленно закрывается без ожидания ответа.');
insert into configuration_email(id,name,value,description) values(32,'mail.smtp.reportsuccess',null,'Если указано значение true, формируется подтверждение об успешной отправке для каждого указанного адресата.');
insert into configuration_email(id,name,value,description) values(33,'mail.smtp.socketFactory',null,'Используется для указания имени фабрики класса, создающего соединение.');
insert into configuration_email(id,name,value,description) values(34,'mail.smtp.socketFactory.class',null,'Используется для указания имени класса, создающего соединение.');
insert into configuration_email(id,name,value,description) values(35,'mail.smtp.socketFactory.fallback',null,'Если указано значение true, то при неудачном создании соединения с использованием mail.smtp.socketFactory используется попытка создать соединение при помощи класса java.net.Socket. Значение по умолчанию: 1');
insert into configuration_email(id,name,value,description) values(36,'mail.smtp.socketFactory.port',null,'Используется для указания порта при соединении с использованием mail.smtp.socketFactory. Если не указан, то будет использован порт по умолчанию.');
insert into configuration_email(id,name,value,description) values(37,'mail.smtp.ssl.enable',null,'Если указано значение true, то при соединении используется SSL и порт SSL по умолчанию. Значение по умолчанию: 0');
insert into configuration_email(id,name,value,description) values(38,'mail.smtp.ssl.checkserveridentity',null,'Если указано значение true, идентификация сервера выполняется по спецификации RFC 2595. Значение по умолчанию: 0');
insert into configuration_email(id,name,value,description) values(39,'mail.smtp.ssl.trust',null,'Если установлено и не указан параметр mail.smtp.socketFactory, то используется  MailSSLSocketFactory. (* для доверия всем узлам или список доверенных узлов). Если не указано, уровень доверия узлам зависит от сертификатов сервера');
insert into configuration_email(id,name,value,description) values(40,'mail.smtp.ssl.socketFactory',null,'Если установлено для класса, расширяющего класс javax.net.ssl.SSLSocketFactory, то этот класс будет использован для создания SMTP SSL соединений.');
insert into configuration_email(id,name,value,description) values(41,'mail.smtp.ssl.socketFactory.class',null,'Если установлено, указывает имя класса, расширяющего класс javax.net.ssl.SSLSocketFactory. Этот класс будет использован для создания SMTP SSL соединений.');
insert into configuration_email(id,name,value,description) values(42,'mail.smtp.ssl.socketFactory.port',null,'Указывает порт для соединения при mail.smtp.ssl.socketFactory. Если не установлено, используется порт по умолчанию.');
insert into configuration_email(id,name,value,description) values(43,'mail.smtp.ssl.protocols',null,'Указывает SSL протоколы, которые используются при соединении SSL.');
insert into configuration_email(id,name,value,description) values(44,'mail.smtp.ssl.ciphersuites',null,'Указывает SSL шифры, которые используются при соединении SSL.');
insert into configuration_email(id,name,value,description) values(45,'mail.smtp.starttls.enable',null,'Если указано значение true, разрешает использование команды STARTTLS. Значение по умолчанию: 0');
insert into configuration_email(id,name,value,description) values(46,'mail.smtp.starttls.required',null,'Если указано значение true, требует requires использование команды STARTTLS. Значение по умолчанию: 0');
insert into configuration_email(id,name,value,description) values(47,'mail.smtp.socks.host',null,'Указывает имя узла, который является SOCKS5 прокси сервером для соединения с почтовым сервером.');
insert into configuration_email(id,name,value,description) values(48,'mail.smtp.socks.port',null,'Указывает порт узла, который является SOCKS5 прокси сервером для соединения с почтовым сервером.');
insert into configuration_email(id,name,value,description) values(49,'mail.smtp.mailextension',null,'Расширяет окончание строки для команды MAIL.');
insert into configuration_email(id,name,value,description) values(50,'mail.smtp.userset',null,'Если указано значение true, команда RSET используется вместо команды NOOP. Значение по умолчанию: 0');
insert into configuration_email(id,name,value,description) values(51,'mail.smtp.noop.strict',null,'Если указано значение true, ожидает обязательного ответа с кодом 250 от команды NOOP об успехе.');
insert into configuration_email(id,name,value,description) values(52,'mail.transport.protocol',null,'Определяет протокол доставки сообщений по-умолчанию');
