insert into event (id,name) values (1,'Создать');
insert into event (id,name) values (2,'Удалить');
insert into event (id,name) values (3,'Рассчитать');
insert into event (id,name) values (4,'Обобщить');
insert into event (id,name) values (5,'Проверить');
insert into event (id,name) values (6,'Сохранить');
insert into event (id,name) values (7,'Импорт данных');
insert into event (id,name) values (8,'Получение данных');
insert into event (id,name) values (9,'Получение защищенных данных');
insert into event (id,name) values (10,'Тестирование скриптов');
insert into event (id,name) values (11,'Миграция из АС "Ведение РНУ"');
insert into event (id,name) values (12,'После создания');
insert into event (id,name) values (26,'Изменить состояние ЭД');
insert into event (id,name) values (101,'Утвердить из "Создана"');
insert into event (id,name) values (102,'Вернуть из "Утверждена" в "Создана"');
insert into event (id,name) values (103,'Принять из "Утверждена"');
insert into event (id,name) values (104,'Вернуть из "Принята" в "Утверждена"');
insert into event (id,name) values (105,'Принять из "Создана"');
insert into event (id,name) values (106,'Вернуть в "Создана"');
insert into event (id,name) values (107,'Подготовить из "Создана"');
insert into event (id,name) values (108,'Вернуть из "Подготовлена" в "Создана"');
insert into event (id,name) values (109,'Принять из "Подготовлена"');
insert into event (id,name) values (110,'Вернуть из "Принята" в "Подготовлена"');
insert into event (id,name) values (111,'Утвердить из "Подготовлена"');
insert into event (id,name) values (112,'Вернуть из "Утверждена" в "Подготовлена"');
insert into event (id,name) values (203,'После принять из "Утверждена"');
insert into event (id,name) values (204,'После вернуть из "Принята" в "Утверждена"');
insert into event (id,name) values (205,'После принять из "Создана"');
insert into event (id,name) values (206,'После вернуть из "Принята" в "Создана"');
insert into event (id,name) values (207,'После принять из "Подготовлена"');
insert into event (id,name) values (208,'После вернуть из "Принята" в "Подготовлена"');
insert into event (id,name) values (209,'После утвердить из "Подготовлена"');
insert into event (id,name) values (210,'После вернуть "Подготовлена" из "Утверждена"');
insert into event (id,name) values (301,'Добавить строку');
insert into event (id,name) values (302,'Загрузка');
insert into event (id,name) values (303,'Удалить строку');
insert into event (id,name) values (401,'Импорт из транспортных файлов');
insert into event (id,name) values (402,'Загрузка транспортных файлов в каталог загрузки');
insert into event (id,name) values (501,'Вход пользователя в Систему');
insert into event (id,name) values (502,'Выход пользователя из Системы');
insert into event (id,name) values (503,'Взаимодействие с внешней АС');
insert into event (id,name) values (601,'Архивирование журнала событий');
insert into event (id,name) values (650,'Отправка email');
insert into event (id,name) values (701,'Версия создана');
insert into event (id,name) values (702,'Версия изменена');
insert into event (id,name) values (703,'Версия введена в действие');
insert into event (id,name) values (704,'Версия выведена из действия');
insert into event (id,name) values (705,'Версия удалена');
insert into event (id,name) values (801,'Вход пользователя в модуль');
insert into event (id,name) values (802,'Выход пользователя из модуля');
insert into event (id,name) values (810,'Загрузка данных о договорах обеспечения');
insert into event (id,name) values (811,'Загрузка данных о клиентах');
insert into event (id,name) values (812,'Загрузка данных о платежах');
insert into event (id,name) values (813,'Загрузка справочника');
insert into event (id,name) values (820,'Создание анкеты клиента');
insert into event (id,name) values (821,'Редактирование анкеты клиента');
insert into event (id,name) values (830,'Создание договора гарантии');
insert into event (id,name) values (831,'Редактирование договора гарантии');
insert into event (id,name) values (832,'Закрытие договора гарантии');
insert into event (id,name) values (840,'Создание договора обеспечения');
insert into event (id,name) values (841,'Редактирование договора обеспечения');
insert into event (id,name) values (842,'Закрытие договора обеспечения');
insert into event (id,name) values (850,'Создание задачи формирования РНУ-23');
insert into event (id,name) values (860,'Создание задачи формирования отчета');
insert into event (id,name) values (901,'Создание подразделения');
insert into event (id,name) values (902,'Модификация подразделения');
insert into event (id,name) values (903,'Удаление подразделения');
insert into event (id,name) values (904,'Импорт скриптов');
insert into event (id,name) values (951,'Редактирование конфигурационного параметра');
insert into event (id,name) values (960,'Удаление блокировки');
