
package com.aplana.sbrf.taxaccounting.web.module.department.ws.departmentws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DepartmentWS", targetNamespace = "http://taxaccounting.sbrf.aplana.com/DepartmentWS/")
public class DepartmentWS_Service
    extends Service
{

    private final static Logger logger = Logger.getLogger(DepartmentWS_Service.class.getName());

    public DepartmentWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartmentWS_Service(String wsdlUrl)  throws MalformedURLException{
        super(
                new URL(null, wsdlUrl),
                new QName("http://taxaccounting.sbrf.aplana.com/DepartmentWS/", "DepartmentWS")
        );
    }

    /**
     * 
     * @return
     *     returns DepartmentWS
     */
    @WebEndpoint(name = "DepartmentWSPort")
    public DepartmentWS getDepartmentWSPort() {
        return super.getPort(new QName("http://taxaccounting.sbrf.aplana.com/DepartmentWS/", "DepartmentWSPort"), DepartmentWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepartmentWS
     */
    @WebEndpoint(name = "DepartmentWSPort")
    public DepartmentWS getDepartmentWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://taxaccounting.sbrf.aplana.com/DepartmentWS/", "DepartmentWSPort"), DepartmentWS.class, features);
    }

}
