comment on materialized view mv_fias_area_act is 'Актуальные районы из справочника ФИАС';
comment on column MV_FIAS_AREA_ACT.ID is 'Уникальный идентификатор';
comment on column MV_FIAS_AREA_ACT.FORMALNAME is 'Формализованное наименование';
comment on column MV_FIAS_AREA_ACT.REGIONCODE is 'Код региона';
comment on column MV_FIAS_AREA_ACT.LIVESTATUS is 'Статус актуальности ФИАС: 1 - актуальная, 0 - устаревшая';
comment on column MV_FIAS_AREA_ACT.CURRSTATUS is 'Статус актуальности КЛАДР: 0 - актуальная, ..';
comment on column MV_FIAS_AREA_ACT.POSTALCODE is 'Почтовый индекс';
comment on column MV_FIAS_AREA_ACT.PARENTGUID is 'Идентификатор родительского объекта';
comment on column MV_FIAS_AREA_ACT.AOID is 'Идентификатор объекта';
comment on column MV_FIAS_AREA_ACT.SHORTNAME is 'Тип адресного объекта';
comment on column MV_FIAS_AREA_ACT.AOLEVEL is 'Уровень объекта';
comment on column MV_FIAS_AREA_ACT.FNAME is 'Наименование, адаптированное для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_AREA_ACT.FTYPE is 'Тип, адаптированный для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_AREA_ACT.HAS_CHILD is 'Наличие дочерних элементов';

comment on materialized view mv_fias_city_act is 'Актуальные города из справочника ФИАС';
comment on column MV_FIAS_CITY_ACT.ID is 'Уникальный идентификатор';
comment on column MV_FIAS_CITY_ACT.FORMALNAME is 'Формализованное наименование';
comment on column MV_FIAS_CITY_ACT.REGIONCODE is 'Код региона';
comment on column MV_FIAS_CITY_ACT.LIVESTATUS is 'Статус актуальности ФИАС: 1 - актуальная, 0 - устаревшая';
comment on column MV_FIAS_CITY_ACT.CURRSTATUS is 'Статус актуальности КЛАДР: 0 - актуальная, ..';
comment on column MV_FIAS_CITY_ACT.POSTALCODE is 'Почтовый индекс';
comment on column MV_FIAS_CITY_ACT.PARENTGUID is 'Идентификатор родительского объекта';
comment on column MV_FIAS_CITY_ACT.AOID is 'Идентификатор объекта';
comment on column MV_FIAS_CITY_ACT.SHORTNAME is 'Тип адресного объекта';
comment on column MV_FIAS_CITY_ACT.AOLEVEL is 'Уровень объекта';
comment on column MV_FIAS_CITY_ACT.FNAME is 'Наименование, адаптированное для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_CITY_ACT.FTYPE is 'Тип, адаптированный для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_CITY_ACT.HAS_CHILD is 'Наличие дочерних элементов';

comment on materialized view mv_fias_locality_act is 'Актуальные населенные пункты из справочника ФИАС';
comment on column MV_FIAS_LOCALITY_ACT.ID is 'Уникальный идентификатор';
comment on column MV_FIAS_LOCALITY_ACT.FORMALNAME is 'Формализованное наименование';
comment on column MV_FIAS_LOCALITY_ACT.REGIONCODE is 'Код региона';
comment on column MV_FIAS_LOCALITY_ACT.LIVESTATUS is 'Статус актуальности ФИАС: 1 - актуальная, 0 - устаревшая';
comment on column MV_FIAS_LOCALITY_ACT.CURRSTATUS is 'Статус актуальности КЛАДР: 0 - актуальная, ..';
comment on column MV_FIAS_LOCALITY_ACT.POSTALCODE is 'Почтовый индекс';
comment on column MV_FIAS_LOCALITY_ACT.PARENTGUID is 'Идентификатор родительского объекта';
comment on column MV_FIAS_LOCALITY_ACT.AOID is 'Идентификатор объекта';
comment on column MV_FIAS_LOCALITY_ACT.SHORTNAME is 'Тип адресного объекта';
comment on column MV_FIAS_LOCALITY_ACT.AOLEVEL is 'Уровень объекта';
comment on column MV_FIAS_LOCALITY_ACT.FNAME is 'Наименование, адаптированное для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_LOCALITY_ACT.FTYPE is 'Тип, адаптированный для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_LOCALITY_ACT.HAS_CHILD is 'Наличие дочерних элементов';

comment on materialized view mv_fias_street_act is 'Актуальные улицы из справочника ФИАС';
comment on column MV_FIAS_STREET_ACT.ID is 'Уникальный идентификатор';
comment on column MV_FIAS_STREET_ACT.FORMALNAME is 'Формализованное наименование';
comment on column MV_FIAS_STREET_ACT.REGIONCODE is 'Код региона';
comment on column MV_FIAS_STREET_ACT.LIVESTATUS is 'Статус актуальности ФИАС: 1 - актуальная, 0 - устаревшая';
comment on column MV_FIAS_STREET_ACT.CURRSTATUS is 'Статус актуальности КЛАДР: 0 - актуальная, ..';
comment on column MV_FIAS_STREET_ACT.POSTALCODE is 'Почтовый индекс';
comment on column MV_FIAS_STREET_ACT.PARENTGUID is 'Идентификатор родительского объекта';
comment on column MV_FIAS_STREET_ACT.AOID is 'Идентификатор объекта';
comment on column MV_FIAS_STREET_ACT.SHORTNAME is 'Тип адресного объекта';
comment on column MV_FIAS_STREET_ACT.AOLEVEL is 'Уровень объекта';
comment on column MV_FIAS_STREET_ACT.FNAME is 'Наименование, адаптированное для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_STREET_ACT.FTYPE is 'Тип, адаптированный для проверки адреса (строчными буквами, без пробелов)';
comment on column MV_FIAS_STREET_ACT.HAS_CHILD is 'Наличие дочерних элементов';
