
package com.aplana.sbrf.taxaccounting.web.module.department.ws.departmentmsendpoint;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DepartmentManagementService", targetNamespace = "http://taxaccounting.sbrf.aplana.com/DepartmentManagementService/")
public interface DepartmentManagementService {


    /**
     * 
     * @return
     *     returns com.aplana.sbrf.taxaccounting.web.module.department.ws.departmentmsendpoint.TaxDepartmentChanges
     */
    @WebMethod(action = "http://taxaccounting.sbrf.aplana.com/DepartmentManagementService/requestAllChanges")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestAllChanges", targetNamespace = "http://taxaccounting.sbrf.aplana.com/DepartmentManagementService/", className = "com.aplana.sbrf.taxaccounting.web.module.department.ws.departmentmsendpoint.RequestAllChanges")
    @ResponseWrapper(localName = "requestAllChangesResponse", targetNamespace = "http://taxaccounting.sbrf.aplana.com/DepartmentManagementService/", className = "com.aplana.sbrf.taxaccounting.web.module.department.ws.departmentmsendpoint.RequestAllChangesResponse")
    public TaxDepartmentChanges requestAllChanges();

}
