DECLARE 
  v_id NUMBER;
BEGIN
  v_id := SEQ_SEC_USER.NEXTVAL;

  INSERT INTO SEC_USER(ID, LOGIN, NAME, DEPARTMENT_ID, IS_ACTIVE)
  VALUES(v_id, '&1', '&2', 0, 1);

  INSERT INTO SEC_USER_ROLE(USER_ID, ROLE_ID)
  VALUES(v_id, 14);
END;
/
